Repository EtherealEngine/etherealengine, pull requests merged in 2023-09, with the labels that each got.

#8590 Behave graph cleanup
  packages/editor/src/components/graph/BehaveFlow.tsx
  packages/engine/src/behave-graph/components/BehaveGraphComponent.ts
  packages/engine/src/behave-graph/functions/createECSRegistry.ts
  packages/engine/src/behave-graph/state/BehaveGraphState.ts
  packages/engine/src/behave-graph/systems/BehaveGraphSystem.ts
Labels: verified-contributor

#8643 Fix loop animation regression
  packages/engine/src/avatar/animation/AvatarAnimationGraph.ts
  packages/engine/src/avatar/components/LoopAnimationComponent.ts
  packages/engine/src/avatar/functions/retargetMixamoRig.ts
Labels: verified-contributor

#8646 Networked avatar animation graph cleanup, fixes
  packages/client-core/src/user/components/Panel3D/helperFunctions.ts
  packages/client-core/src/user/components/UserMenu/menus/EmoteMenu.tsx
  packages/engine/src/avatar/animation/AvatarAnimationGraph.ts
  packages/engine/src/avatar/animation/Util.ts
  packages/engine/src/avatar/components/AvatarAnimationComponent.ts
  packages/engine/src/avatar/functions/moveAvatar.ts
  packages/engine/src/avatar/state/AvatarNetworkActions.ts
Labels: verified-contributor

#8651 Ensure that Variant has been set on Model load
  packages/engine/src/scene/components/ModelComponent.ts
  packages/engine/src/scene/components/VariantComponent.tsx
  packages/engine/src/scene/functions/loaders/VariantFunctions.ts
Labels: verified-contributor

#8647 Tests for S3 Storage Provider
  packages/server-core/src/media/file-browser/file-browser.class.ts
  packages/server-core/src/media/file-browser/file-browser.test.ts
  packages/server-core/src/media/storageprovider/local.storage.ts
  packages/server-core/src/projects/scene/scene.test.ts
  packages/server-core/src/user/identity-provider/identity-provider.class.ts
  packages/server-core/src/user/identity-provider/identity-provider.test.ts
Labels: verified-contributor

#8653 fix failing ci tests
  .env.local.default
Labels: verified-contributor

#8649 Networked IK -> FK blending and enhancements
  packages/engine/src/avatar/animation/AvatarAnimationGraph.ts
  packages/engine/src/avatar/components/AvatarIKComponents.ts
  packages/engine/src/avatar/functions/avatarFootHeuristics.ts
  packages/engine/src/avatar/functions/avatarFunctions.ts
  packages/engine/src/avatar/functions/moveAvatar.ts
  packages/engine/src/avatar/state/AvatarNetworkActions.ts
  packages/engine/src/avatar/systems/AvatarAnimationSystem.ts
  packages/engine/src/avatar/systems/AvatarIKTargetSystem.ts
  packages/engine/src/mocap/UpdateIkPose.ts
Labels: verified-contributor

#8652 action nodes
  packages/engine/src/behave-graph/nodes/Profiles/Engine/helper/actionHelper.ts
  packages/engine/src/behave-graph/nodes/Profiles/Engine/helper/componentHelper.ts
  packages/engine/src/behave-graph/nodes/Profiles/Engine/helper/stateHelper.ts
  packages/engine/src/behave-graph/nodes/Profiles/Engine/registerEngineProfile.ts
  packages/hyperflux/functions/ActionFunctions.ts
Labels: verified-contributor

#8648 move registry creation to state
  packages/editor/src/components/graph/BehaveFlow.tsx
  packages/engine/src/behave-graph/nodes/Profiles/Engine/helper/stateHelper.ts
  packages/engine/src/behave-graph/state/BehaveGraphState.ts
  packages/engine/src/behave-graph/systems/BehaveGraphSystem.ts
Labels: verified-contributor

#8477 Behave graph spline nodes
  packages/editor/src/components/graph/ee-flow/components/Flow.tsx
  packages/editor/src/components/inputs/Button.css
  packages/editor/src/components/inputs/Vector3Input.tsx
  packages/editor/src/components/properties/SplineNodeEditor.tsx
  packages/editor/src/components/properties/SplineTrackNodeEditor.tsx
  packages/engine/src/behave-graph/nodes/Profiles/Engine/Events/triggerLoadAsset.ts
  packages/engine/src/behave-graph/nodes/Profiles/Engine/Values/CustomNodes.ts
  packages/engine/src/behave-graph/nodes/Profiles/Engine/Values/EntityNodes.ts
  packages/engine/src/behave-graph/nodes/Profiles/Engine/Values/SplineNodes.ts
  packages/engine/src/behave-graph/nodes/Profiles/Engine/helper/assetHelper.ts
  packages/engine/src/behave-graph/nodes/Profiles/Engine/registerEngineProfile.ts
  packages/engine/src/scene/components/SplineComponent.ts
  packages/engine/src/scene/components/SplineTrackComponent.ts
Labels: verified-contributor

#8661 XR session nodes
  packages/engine/src/behave-graph/nodes/Profiles/Engine/Values/CustomNodes.ts
Labels: verified-contributor

#8634 7461 Optimize avatar load
  packages/engine/src/avatar/components/AvatarDissolveComponent.ts
  packages/engine/src/avatar/components/AvatarEffectComponent.ts
  packages/engine/src/avatar/functions/avatarFunctions.ts
  packages/engine/src/avatar/systems/AvatarLoadingSystem.ts
Labels: verified-contributor

#8054 Added TLS certificate in local MinIO
  .env.local.default
  certs/minio/CAs/public.crt
  certs/minio/README.md
  certs/minio/private.key
  certs/minio/public.crt
  package.json
  packages/instanceserver/src/start.ts
  packages/server-core/src/appconfig.ts
  packages/server-core/src/media/file-browser/file-browser.class.ts
  packages/server-core/src/media/file-browser/file-browser.test.ts
  packages/server-core/src/media/storageprovider/getCachedURL.ts
  packages/server-core/src/media/storageprovider/local.storage.ts
  packages/server-core/src/projects/scene/scene.test.ts
  packages/server-core/src/user/identity-provider/identity-provider.class.ts
  packages/server-core/src/user/identity-provider/identity-provider.test.ts
  packages/server/package.json
  packages/server/src/start.ts
  scripts/build_microk8s.sh
  scripts/build_minikube.sh
  scripts/docker-compose-minio.yml
  scripts/docker-compose.yml
  scripts/konsole_tabs.desktop
  scripts/run-xrengine.sh
  scripts/start-containers.sh
  scripts/start-db.sh
Labels: verified-contributor

#8671 fixed file browser not visible in admin panel
  packages/editor/src/components/assets/FileBrowserContentPanel.tsx
  packages/editor/src/components/assets/ProjectBrowserPanel.tsx
Labels: verified-contributor

#8589 Changes for project service to use schema, knex & feathers 5
  packages/client-core/src/admin/components/Project/ProjectDrawer.tsx
  packages/client-core/src/admin/components/Project/ProjectFields.tsx
  packages/client-core/src/admin/components/Project/ProjectFilesDrawer.tsx
  packages/client-core/src/admin/components/Project/ProjectTable.tsx
  packages/client-core/src/admin/components/Project/UpdateDrawer.tsx
  packages/client-core/src/admin/components/Project/UserPermissionDrawer.tsx
  packages/client-core/src/admin/components/Setting/Project.tsx
  packages/client-core/src/admin/services/ProjectUpdateService.ts
  packages/client-core/src/common/services/ProjectService.ts
  packages/client-core/src/components/World/EngineHooks.tsx
  packages/client/src/pages/_app.tsx
  packages/client/src/pages/_app_tw.tsx
  packages/client/src/pages/capture/capture.tsx
  packages/common/src/interfaces/ProjectInterface.ts
  packages/common/src/interfaces/ProjectPackageJsonType.ts
  packages/editor/src/components/projects/EditPermissionsDialog.tsx
  packages/editor/src/components/projects/ProjectsPage.tsx
  packages/editor/src/functions/projectFunctions.tsx
  packages/editor/src/pages/EditorPage.tsx
  packages/engine/src/schemas/projects/project-build.schema.ts
  packages/engine/src/schemas/projects/project.schema.ts
  packages/engine/src/schemas/projects/projects.schema.ts
  packages/instanceserver/src/channels.ts
  packages/server-core/src/hooks/project-permission-authenticate.ts
  packages/server-core/src/hooks/verify-project-owner.ts
  packages/server-core/src/projects/project-github-push/project-github-push.class.ts
  packages/server-core/src/projects/project-permission/project-permission.class.ts
  packages/server-core/src/projects/project-permission/project-permission.test.ts
  packages/server-core/src/projects/project/github-helper.ts
  packages/server-core/src/projects/project/migrations/20230828152702_project.ts
  packages/server-core/src/projects/project/project-helper.ts
  packages/server-core/src/projects/project/project.class.ts
  packages/server-core/src/projects/project/project.docs.ts
  packages/server-core/src/projects/project/project.hooks.ts
  packages/server-core/src/projects/project/project.model.ts
  packages/server-core/src/projects/project/project.resolvers.ts
  packages/server-core/src/projects/project/project.test.ts
  packages/server-core/src/projects/project/project.ts
  packages/server-core/src/projects/projects/projects.class.ts
  packages/server-core/src/projects/projects/projects.hooks.ts
  packages/server-core/src/projects/projects/projects.resolvers.ts
  packages/server-core/src/projects/scene/scene.class.ts
  packages/server-core/src/projects/scene/scene.service.ts
  packages/server-core/src/projects/scene/scene.test.ts
  packages/server-core/src/projects/services.ts
  packages/server-core/src/route/route/route.test.ts
  packages/server-core/src/seeder.ts
  packages/server-core/src/setting/project-setting/project-setting.class.ts
  packages/server-core/src/user/avatar/avatar-helper.test.ts
  packages/server/src/start.ts
  packages/ui/src/pages/Capture/index.stories.tsx
  packages/ui/src/pages/Chat/chat.tsx
  scripts/install-projects.js
  scripts/push-project.ts
  scripts/update-cronjob-image.ts
  scripts/update-project.ts
Labels: verified-contributor

#8642 Fix for project files using S3 URL
  packages/server-core/src/appconfig.ts
  packages/server-core/src/media/file-browser/file-browser.class.ts
  packages/server-core/src/setting/aws-setting/aws-setting.seed.ts
Labels: verified-contributor

#8678 Fixed issue with S3 putObject in MinIO
  package.json
  packages/client/package.json
  packages/instanceserver/package.json
  packages/server-core/package.json
  packages/server-core/src/media/storageprovider/s3.storage.ts
  packages/server/package.json
  packages/taskserver/package.json
Labels: verified-contributor

#8674 Unify Storage Provider Dev Commands
  .env.local.default
  package.json
  packages/server-core/src/appconfig.ts
  packages/server-core/src/createApp.ts
  packages/server-core/src/media/FileUtil.test.ts
  packages/server-core/src/media/file-browser/file-browser.test.ts
  packages/server-core/src/media/storageprovider/local.storage.ts
  packages/server-core/src/media/storageprovider/s3.storage.ts
  packages/server-core/src/projects/scene/scene-schema-parse.test.ts
  packages/server-core/tests/storageprovider/storageprovider.test.ts
  scripts/docker-compose-minio.yml
Labels: verified-contributor

#8483 Changes for channel-user service to use schema, knex & feathers 5
  packages/client-core/src/social/services/ChannelService.ts
  packages/common/src/dbmodels/ChannelUser.ts
  packages/common/src/dbmodels/UserInterface.ts
  packages/engine/src/schemas/interfaces/Channel.ts
  packages/engine/src/schemas/interfaces/ChannelUser.ts
  packages/engine/src/schemas/social/channel-user.schema.ts
  packages/instanceserver/src/channels.ts
  packages/server-core/src/all.model.ts
  packages/server-core/src/hooks/add-associations.ts
  packages/server-core/src/hooks/channel-permission-authenticate.ts
  packages/server-core/src/social/channel-user/channel-user.class.ts
  packages/server-core/src/social/channel-user/channel-user.docs.ts
  packages/server-core/src/social/channel-user/channel-user.hooks.ts
  packages/server-core/src/social/channel-user/channel-user.model.ts
  packages/server-core/src/social/channel-user/channel-user.resolvers.ts
  packages/server-core/src/social/channel-user/channel-user.test.ts
  packages/server-core/src/social/channel-user/channel-user.ts
  packages/server-core/src/social/channel-user/migrations/20230817133703_channel-user.ts
  packages/server-core/src/social/channel/channel.class.ts
  packages/server-core/src/social/channel/channel.hooks.ts
  packages/server-core/src/social/channel/channel.model.ts
  packages/server-core/src/social/channel/channel.service.ts
  packages/server-core/src/social/channel/channel.test.ts
  packages/server-core/src/social/message/message.ts
  packages/server-core/src/social/services.ts
  packages/server-core/src/user/accept-invite/accept-invite.class.ts
Labels: verified-contributor

#8690 fix file browser scroll
  packages/editor/src/components/assets/styles.module.scss
Labels: verified-contributor

#8691 Changes to fix commitDate being null
  packages/server-core/src/projects/project/project-helper.ts
Labels: verified-contributor

#8664 fix: make scene `save as` visible
  packages/editor/src/components/EditorContainer.tsx
  packages/editor/src/components/dialogs/PreviewDialog.tsx
  packages/editor/src/components/dialogs/SaveNewSceneDialog.tsx
  packages/editor/src/functions/takeScreenshot.ts
Labels: verified-contributor

#8695 Fixing some $like searches on projects
  packages/server-core/src/projects/project/project-helper.ts
  packages/server-core/src/projects/project/project.class.ts
Labels: verified-contributor

#8384 Fixing Chat Page UI
  packages/ui/src/components/Chat/ChatSection.tsx
  packages/ui/src/components/Chat/Message.tsx
Labels: verified-contributor

#8659 Hiding Update Engine and Build Status buttons on local
  packages/client-core/src/admin/components/Project/index.tsx
Labels: verified-contributor

#8675 Fixes for loop animation component and retargeting
  packages/engine/src/avatar/components/LoopAnimationComponent.ts
  packages/engine/src/avatar/functions/avatarFunctions.ts
  packages/engine/src/avatar/functions/retargetMixamoRig.ts
Labels: verified-contributor

#8707 Prevent asset load errors from blocking scene loading
  packages/engine/src/scene/components/ModelComponent.ts
Labels: verified-contributor

#8692 Fade to Video
  packages/engine/src/behave-graph/nodes/Profiles/Engine/Values/CustomNodes.ts
  packages/engine/src/camera/CameraState.ts
  packages/engine/src/camera/systems/CameraFadeBlackEffectSystem.ts
  packages/engine/src/renderer/materials/functions/LoadVideoTexture.ts
Labels: verified-contributor

#8725 Add shadow max radius
  packages/engine/src/scene/systems/ShadowSystem.tsx
Labels: verified-contributor

#8727 Scene dispose fixes
  packages/client-core/src/systems/LoadingUISystem.tsx
  packages/editor/src/components/assets/AssetsPreviewPanel.tsx
  packages/editor/src/components/assets/ScenesPanel.tsx
  packages/editor/src/systems/EditorControlSystem.tsx
  packages/engine/src/assets/functions/createReadableTexture.ts
  packages/engine/src/common/functions/OnBeforeCompilePlugin.ts
  packages/engine/src/scene/classes/TransformGizmo.ts
  packages/engine/src/scene/components/GroupComponent.tsx
  packages/engine/src/scene/components/PortalComponent.ts
  packages/engine/src/scene/systems/SceneObjectSystem.tsx
Labels: verified-contributor

#8703 Fix skinned mesh lag spikes
  packages/editor/src/components/properties/ModelNodeEditor.tsx
  packages/engine/src/scene/components/ModelComponent.ts
Labels: verified-contributor

#8676 Changes for accept-invite service to use schema, knex & feathers 5
  packages/client-core/src/social/services/InviteService.ts
  packages/engine/src/schemas/user/accept-invite.schema.ts
  packages/server-core/src/user/accept-invite/accept-invite.class.ts
  packages/server-core/src/user/accept-invite/accept-invite.docs.ts
  packages/server-core/src/user/accept-invite/accept-invite.ts
  packages/server-core/src/user/auth-management/auth-management.utils.ts
  packages/server-core/src/user/services.ts
Labels: verified-contributor

#8736 Fix project-setting patch
  packages/client-core/src/admin/components/Setting/Project.tsx
  packages/server-core/src/projects/project/project.class.ts
  packages/server-core/src/setting/project-setting/project-setting.class.ts
Labels: verified-contributor

#8667 Use multipart upload on large files
  packages/common/src/constants/FileSizeConstants.ts
  packages/server-core/src/media/recursive-archiver/archiver.class.ts
  packages/server-core/src/media/storageprovider/local.storage.ts
  packages/server-core/src/media/storageprovider/s3.storage.ts
  packages/server-core/src/media/storageprovider/storageprovider.interface.ts
  packages/server-core/src/util/fsHelperFunctions.ts
Labels: verified-contributor

#8677 chnage input type
  packages/engine/src/behave-graph/nodes/Profiles/Engine/Values/CustomNodes.ts
Labels: verified-contributor

#8699 post processing component in the shelf
  packages/client-core/i18n/en/editor.json
  packages/editor/src/components/element/ElementList.tsx
  packages/editor/src/components/properties/PostProcessingSettingsEditor.tsx
Labels: verified-contributor

#8706 8702 fix leaving web xr
  packages/client-core/src/systems/WidgetUISystem.ts
  packages/engine/src/avatar/systems/AvatarIKTargetSystem.ts
  packages/engine/src/xr/XRCameraSystem.ts
Labels: bug, verified-contributor

#8719 Split Shadow Node Editor from Model Node Editor
  packages/editor/src/components/properties/ModelNodeEditor.tsx
  packages/editor/src/components/properties/ShadowProperties.tsx
  packages/editor/src/functions/ComponentEditors.tsx
Labels: verified-contributor

#8733 Skinned mesh ECS bounding box frustum culling
  packages/engine/src/scene/components/ModelComponent.ts
  packages/engine/src/scene/systems/SceneObjectSystem.tsx
  packages/engine/src/transform/systems/TransformSystem.ts
Labels: verified-contributor

#8730 Fix of cc getting stucked in reinit
  packages/server-core/src/seeder.ts
  packages/server-core/src/sequelize.ts
  scripts/start-containers.sh
Labels: verified-contributor

#8766 Add bounding box calculation for avatars
  packages/engine/src/transform/systems/TransformSystem.ts
Labels: verified-contributor

#8543 Add Meshoptimizer (GLTFPack) to model transform pipeline
  packages/client-core/i18n/en/editor.json
  packages/editor/src/components/properties/GLTFTransformProperties.tsx
  packages/engine/src/assets/classes/ModelTransform.ts
  packages/engine/src/assets/exporters/gltf/extensions/EEMaterialExporterExtension.ts
  packages/engine/src/assets/loaders/gltf/GLTFLoader.js
  packages/engine/src/scene/components/ModelComponent.ts
  packages/server-core/src/assets/extensions/EE_MaterialTransformer.ts
  packages/server-core/src/assets/model-transform/model-transform.helpers.ts
  packages/server/public/loader_decoders/gltfpack
Labels: verified-contributor

#8685 tests: remove explicit local storage tests
  .env.local.default
  packages/common/src/config.ts
  packages/server-core/package.json
  packages/server-core/src/media/file-browser/file-browser.test.ts
  packages/server-core/src/media/storageprovider/local.storage.ts
  packages/server-core/src/media/storageprovider/s3.storage.ts
  packages/server-core/tests/storageprovider/storageprovider.test.ts
Labels: verified-contributor

#8700 chore: speed up documentation checks
  .github/workflows/documentation.yml
Labels: verified-contributor

#8754 Animation race condition fixes
  packages/client-core/i18n/en/editor.json
  packages/editor/src/components/properties/LoopAnimationNodeEditor.tsx
  packages/engine/src/avatar/components/LoopAnimationComponent.ts
  packages/engine/src/avatar/systems/AnimationSystem.ts
  packages/engine/src/behave-graph/nodes/Profiles/Engine/Values/CustomNodes.ts
  packages/engine/src/scene/components/CallbackComponent.ts
Labels: verified-contributor

#8759 Material-panel-fix
  packages/editor/src/components/inputs/TexturePreviewInput.tsx
  packages/editor/src/components/materials/MaterialEditor.tsx
  packages/engine/src/renderer/materials/functions/MaterialPluginFunctions.ts
Labels: verified-contributor

#8698 Changes for email service to use schema, knex & feathers 5
  packages/engine/src/schemas/user/email.schema.ts
  packages/server-core/src/hooks/send-invite.ts
  packages/server-core/src/user/auth-management/auth-management.utils.ts
  packages/server-core/src/user/email/email.docs.ts
  packages/server-core/src/user/email/email.hooks.ts
  packages/server-core/src/user/email/email.ts
  packages/server-core/src/user/services.ts
Labels: verified-contributor

#8750 Changes for verification-event service to use schema, knex & feathers 5
  packages/server-core/src/credential/services.ts
  packages/server-core/src/credential/verification-event/verification-event.class.ts
  packages/server-core/src/credential/verification-event/verification-event.docs.ts
  packages/server-core/src/credential/verification-event/verification-event.hooks.ts
  packages/server-core/src/credential/verification-event/verification-event.model.ts
  packages/server-core/src/credential/verification-event/verification-event.service.ts
Labels: verified-contributor

#8778 Fixed some bugs with the file browser and project paths.
  packages/editor/src/components/assets/FileBrowserContentPanel.tsx
  packages/server-core/src/media/storageprovider/local.storage.ts
  packages/server-core/src/media/storageprovider/s3.storage.ts
  packages/server-core/src/projects/project/downloadProjects.ts
Labels: verified-contributor

#8622 Hyper Link Component
  packages/client-core/i18n/en/editor.json
  packages/editor/src/components/element/ElementList.tsx
  packages/editor/src/components/properties/LinkNodeEditor.tsx
  packages/editor/src/functions/ComponentEditors.tsx
  packages/engine/src/renderer/components/HighlightComponent.ts
  packages/engine/src/scene/SceneClientModule.ts
  packages/engine/src/scene/components/LinkComponent.ts
Labels: verified-contributor

#8755 retired deprecated deltaSeconds, elapsedSeconds, fixedTick, fixedDelt…
  packages/client-core/src/systems/AvatarUISystem.tsx
  packages/client-core/src/systems/WarningUISystem.tsx
  packages/client-core/src/transports/FilteredUsersSystem.ts
  packages/editor/src/components/realtime/EditorInstanceNetworkingSystem.ts
  packages/engine/src/audio/systems/PositionalAudioSystem.tsx
  packages/engine/src/avatar/functions/autopilotFunctions.ts
  packages/engine/src/avatar/functions/moveAvatar.ts
  packages/engine/src/avatar/systems/AvatarControllerSystem.ts
  packages/engine/src/avatar/systems/AvatarLoadingSystem.ts
  packages/engine/src/avatar/systems/AvatarTeleportSystem.ts
  packages/engine/src/avatar/systems/FlyControlSystem.ts
  packages/engine/src/camera/systems/CameraFadeBlackEffectSystem.ts
  packages/engine/src/camera/systems/CameraInputSystem.ts
  packages/engine/src/camera/systems/CameraSystem.tsx
  packages/engine/src/ecs/classes/Engine.ts
  packages/engine/src/interaction/systems/GrabbableSystem.tsx
  packages/engine/src/interaction/systems/InteractiveSystem.ts
  packages/engine/src/interaction/systems/MediaControlSystem.ts
  packages/engine/src/renderer/WebGLRendererSystem.ts
  packages/engine/src/renderer/materials/constants/plugins/NoiseOffsetPlugin.ts
  packages/engine/src/scene/systems/ParticleSystemSystem.ts
  packages/engine/src/xr/XRAnchorSystem.ts
Labels: verified-contributor

#8776 Restore model avoid occlusion toggle
  packages/engine/src/scene/components/ModelComponent.ts
Labels: verified-contributor

#8767 Avatar animation system optimizations
  packages/engine/src/avatar/functions/avatarFunctions.ts
  packages/engine/src/avatar/systems/AvatarAnimationSystem.ts
Labels: verified-contributor

#8773 fixed shelf heading scrolling for file browser
  packages/editor/src/components/assets/FileBrowserContentPanel.tsx
  packages/editor/src/components/assets/styles.module.scss
Labels: verified-contributor

#8775 drop on panel fix
  packages/editor/src/components/assets/FileBrowserContentPanel.tsx
Labels: verified-contributor

#8780 Fixed system path loading for issue in projects.
  packages/projects/loadSystemInjection.ts
Labels: verified-contributor

#8686 Removal of auth-management service
  packages/client-core/src/user/components/Auth/ConfirmEmail.tsx
  packages/client-core/src/user/components/Auth/ConfirmEmailApp.tsx
  packages/client-core/src/user/components/Auth/VerifyEmail.tsx
  packages/client-core/src/user/components/MagicLink/AuthMagicLink.tsx
  packages/client-core/src/user/services/AuthService.ts
  packages/client/src/pages/auth/authRoutes.tsx
  packages/client/src/pages/auth/confirm.tsx
  packages/server-core/src/hooks/send-invite.ts
  packages/server-core/src/user/auth-management/auth-management.class.ts
  packages/server-core/src/user/auth-management/auth-management.hooks.ts
  packages/server-core/src/user/auth-management/auth-management.notifier.ts
  packages/server-core/src/user/auth-management/auth-management.service.ts
  packages/server-core/src/user/auth-management/auth-management.utils.ts
  packages/server-core/src/user/magic-link/magic-link.class.ts
  packages/server-core/src/user/services.ts
Labels: verified-contributor

#8770 Changes for instance-provision service to use schema, knex & feathers 5
  packages/client-core/src/common/services/LocationInstanceConnectionService.ts
  packages/client-core/src/common/services/MediaInstanceConnectionService.ts
  packages/editor/src/components/realtime/EditorActiveInstanceService.ts
  packages/engine/src/schemas/networking/instance-provision.schema.ts
  packages/server-core/src/networking/instance-provision/instance-provision.class.ts
  packages/server-core/src/networking/instance-provision/instance-provision.docs.ts
  packages/server-core/src/networking/instance-provision/instance-provision.ts
  packages/server-core/src/networking/services.ts
Labels: verified-contributor

#8772 Optimize, Fix, and improve
  packages/client-core/src/components/World/EngineHooks.tsx
  packages/engine/src/ecs/functions/SystemFunctions.tsx
  packages/engine/src/renderer/functions/RenderSettingsFunction.ts
  packages/engine/src/scene/systems/ShadowSystem.tsx
Labels: verified-contributor

#8786 move set loading true to appropiate position
  packages/editor/src/components/assets/FileBrowserContentPanel.tsx
Labels: verified-contributor

#8784 Use dynamic tag instead of avatar query, fix box compute error
  packages/engine/src/avatar/functions/spawnAvatarReceptor.ts
  packages/engine/src/transform/systems/TransformSystem.ts
Labels: verified-contributor

#8779 Purge all commit history from gh-pages before pushing from the "dev" branch.
  .github/workflows/documentation.yml
Labels: documentation, verified-contributor

#8795 Fix the docs workflow while purging git commit history.
  .github/workflows/documentation.yml
Labels: verified-contributor

#8796 rigidbody check for set transform node
  packages/engine/src/behave-graph/nodes/Profiles/Engine/Values/EntityNodes.ts
Labels: verified-contributor

#8822 File Browser Search Bar
  packages/editor/src/components/assets/FileBrowserContentPanel.tsx
  packages/editor/src/components/assets/styles.module.scss
Labels: verified-contributor

#8823 Track Missing Materials in Material Library
  packages/client-core/src/components/Debug/index.tsx
  packages/engine/src/assets/exporters/gltf/GLTFExporter.js
  packages/engine/src/assets/exporters/gltf/extensions/EEMaterialExporterExtension.ts
  packages/engine/src/assets/loaders/gltf/GLTFLoader.js
  packages/engine/src/assets/loaders/gltf/extensions/EEMaterialImporterExtension.ts
  packages/engine/src/renderer/materials/components/MaterialComponent.ts
  packages/engine/src/renderer/materials/functions/MaterialLibraryFunctions.ts
  packages/engine/src/renderer/materials/systems/MaterialLibrarySystem.tsx
  packages/engine/src/scene/systems/SceneObjectSystem.tsx
  packages/server-core/src/assets/extensions/EE_MaterialTransformer.ts
Labels: verified-contributor

#8781 fix(file browser): file size from s3 storage
  packages/editor/src/components/assets/FileBrowserContentPanel.tsx
  packages/editor/src/functions/utils.ts
  packages/engine/src/schemas/media/file-browser.schema.ts
  packages/server-core/src/media/file-browser/file-browser.test.ts
  packages/server-core/src/media/storageprovider/ipfs.storage.ts
  packages/server-core/src/media/storageprovider/local.storage.ts
  packages/server-core/src/media/storageprovider/s3.storage.ts
  packages/server-core/src/media/storageprovider/storageprovider.interface.ts
  packages/server-core/tests/storageprovider/storageprovider.test.ts
Labels: verified-contributor

#8824 removed Engine.instance.priorityAvatarEntities
  packages/engine/src/avatar/systems/AvatarAnimationSystem.ts
  packages/engine/src/ecs/classes/Engine.ts
Labels: verified-contributor

#8825 tests: throttling configurations in minio
  scripts/docker-compose-minio.yml
Labels: verified-contributor

#8655 fix(media nodeeditor): add filebrowserinput in array input group
  packages/client-core/i18n/en/editor.json
  packages/editor/src/components/inputs/ArrayInputGroup.module.scss
  packages/editor/src/components/inputs/ArrayInputGroup.tsx
  packages/editor/src/components/inputs/InputGroup.tsx
  packages/editor/src/components/inputs/NumericStepperInput.tsx
  packages/editor/src/components/properties/MediaNodeEditor.tsx
  packages/editor/src/components/properties/VolumetricNodeEditor.tsx
Labels: verified-contributor

#8841 hot-fix(ci): fix type error in input group
  packages/editor/src/components/inputs/InputGroup.tsx
Labels: verified-contributor

#8735 feat(CI): speedup branch-build github action
  .github/workflows/branch-build.yml
Labels: verified-contributor

#8832 Change default shadow resolution for non mobile to 2k
  packages/engine/src/renderer/RendererState.ts
Labels: verified-contributor

#8783 Merge server info and server logs to pods service
  packages/client-core/src/admin/common/variables/server.ts
  packages/client-core/src/admin/components/Server/ServerItemCard.tsx
  packages/client-core/src/admin/components/Server/ServerLogs.tsx
  packages/client-core/src/admin/components/Server/ServerTable.tsx
  packages/client-core/src/admin/components/Server/index.tsx
  packages/client-core/src/admin/services/ServerInfoQuery.ts
  packages/engine/src/schemas/cluster/pods.schema.ts
  packages/engine/src/schemas/cluster/server-logs.schema.ts
  packages/server-core/src/cluster/pods/pods-helper.ts
  packages/server-core/src/cluster/pods/pods.class.ts
  packages/server-core/src/cluster/pods/pods.docs.ts
  packages/server-core/src/cluster/pods/pods.hooks.ts
  packages/server-core/src/cluster/pods/pods.ts
  packages/server-core/src/cluster/server-info/server-info.docs.ts
  packages/server-core/src/cluster/server-info/server-info.ts
  packages/server-core/src/cluster/server-logs/server-logs-helper.ts
  packages/server-core/src/cluster/server-logs/server-logs.class.ts
  packages/server-core/src/cluster/server-logs/server-logs.docs.ts
  packages/server-core/src/cluster/server-logs/server-logs.ts
  packages/server-core/src/cluster/services.ts
  packages/server-core/src/projects/project/project-helper.ts
Labels: verified-contributor

#8844 Standardize Admin Table to Feathers Hooks Pagination
  packages/client-core/src/admin/common/Table.tsx
  packages/client-core/src/admin/common/variables/projects.ts
  packages/client-core/src/admin/components/Avatars/AvatarTable.tsx
  packages/client-core/src/admin/components/Channels/ChannelTable.tsx
  packages/client-core/src/admin/components/Instance/InstanceDrawer.tsx
  packages/client-core/src/admin/components/Instance/InstanceTable.tsx
  packages/client-core/src/admin/components/Invite/AdminInvites.tsx
  packages/client-core/src/admin/components/Location/LocationTable.tsx
  packages/client-core/src/admin/components/Project/BuildStatusDrawer.tsx
  packages/client-core/src/admin/components/Project/ProjectTable.tsx
  packages/client-core/src/admin/components/Recordings/RecordingsTable.tsx
  packages/client-core/src/admin/components/Resources/ResourceTable.tsx
  packages/client-core/src/admin/components/Routes/RouteTable.tsx
  packages/client-core/src/admin/components/Server/ServerTable.tsx
  packages/client-core/src/admin/components/Users/UserDrawer.tsx
  packages/client-core/src/admin/components/Users/UserTable.tsx
  packages/client-core/src/admin/services/ResourceService.ts
  packages/client-core/src/social/services/InviteService.ts
  packages/engine/src/common/functions/FeathersHooks.tsx
  packages/server-core/src/projects/project/project.class.ts
  packages/ui/src/components/tailwind/RecordingList/index.tsx
Labels: verified-contributor

#8839 Avatar Loading Fail Fallback
  packages/client-core/src/components/World/EngineHooks.tsx
  packages/client-core/src/user/components/UserMenu/menus/AvatarSelectMenu.tsx
  packages/client-core/src/user/services/AvatarService.ts
  packages/engine/src/avatar/functions/avatarFunctions.ts
  packages/engine/src/avatar/state/AvatarNetworkState.tsx
  packages/engine/src/mocap/solveMotionCapturePose.ts
  packages/engine/src/networking/interfaces/WorldState.ts
Labels: verified-contributor

#8845 moving pointerState and pointerScreenRaycaster
  packages/client-core/src/systems/AvatarUISystem.tsx
  packages/editor/src/systems/EditorControlSystem.tsx
  packages/engine/src/avatar/functions/autopilotFunctions.ts
  packages/engine/src/avatar/systems/AvatarInputSystem.ts
  packages/engine/src/avatar/systems/FlyControlSystem.ts
  packages/engine/src/camera/systems/CameraInputSystem.ts
  packages/engine/src/ecs/classes/Engine.ts
  packages/engine/src/input/state/InputState.ts
  packages/engine/src/input/systems/ClientInputSystem.ts
  packages/engine/src/interaction/systems/MediaControlSystem.ts
  packages/engine/src/xrui/systems/XRUISystem.ts
Labels: verified-contributor

#8849 xrframe moved
  packages/client-core/src/systems/WidgetUISystem.ts
  packages/client-core/src/systems/createHeightAdjustmentWidget.tsx
  packages/engine/src/avatar/functions/applyInputSourcePoseToIKTargets.ts
  packages/engine/src/avatar/functions/moveAvatar.ts
  packages/engine/src/avatar/systems/AvatarTeleportSystem.ts
  packages/engine/src/camera/systems/CameraInputSystem.ts
  packages/engine/src/common/functions/Timer.ts
  packages/engine/src/ecs/classes/Engine.ts
  packages/engine/src/input/systems/ClientInputSystem.ts
  packages/engine/src/renderer/WebGLRendererSystem.ts
  packages/engine/src/transform/systems/TransformSystem.ts
  packages/engine/src/transform/updateWorldOrigin.ts
  packages/engine/src/xr/8thwall/XR8.ts
  packages/engine/src/xr/8thwall/XR8WebXRProxy.ts
  packages/engine/src/xr/XRAnchorSystem.ts
  packages/engine/src/xr/XRCameraSystem.ts
  packages/engine/src/xr/XRCameraViewSystem.ts
  packages/engine/src/xr/XRDepthOcclusion.tsx
  packages/engine/src/xr/XRDetectedPlanesSystem.ts
  packages/engine/src/xr/XRLightProbeSystem.ts
  packages/engine/src/xr/XRPersistentAnchorSystem.ts
  packages/engine/src/xr/XRSessionFunctions.ts
  packages/engine/src/xr/XRState.ts
  packages/engine/src/xrui/systems/XRUISystem.ts
Labels: verified-contributor

#8746 Changes for project-setting service to use schema, knex & feathers 5
  packages/client-core/src/admin/components/Setting/Project.tsx
  packages/client-core/src/common/services/ProjectService.ts
  packages/editor/src/functions/projectFunctions.tsx
  packages/server-core/src/hooks/project-permission-authenticate.ts
  packages/server-core/src/projects/project-permission/project-permission.class.ts
  packages/server-core/src/projects/project/project-helper.ts
  packages/server-core/src/projects/project/project.class.ts
  packages/server-core/src/projects/project/project.resolvers.ts
  packages/server-core/src/projects/project/project.test.ts
  packages/server-core/src/projects/scene/scene.class.ts
  packages/server-core/src/projects/scene/scene.service.ts
  packages/server-core/src/projects/scene/scene.test.ts
  packages/server-core/src/setting/project-setting/project-setting.class.ts
  packages/server-core/src/setting/project-setting/project-setting.hooks.ts
  packages/server-core/src/setting/project-setting/project-setting.service.ts
  packages/server-core/src/setting/service.ts
  scripts/update-cronjob-image.ts
Labels: verified-contributor

#8666 Changes for channel service to use schema, knex & feathers 5
  packages/client-core/i18n/en/admin.json
  packages/client-core/src/admin/components/Channels/ChannelDrawer.tsx
  packages/client-core/src/admin/components/Channels/ChannelTable.tsx
  packages/client-core/src/common/services/MediaInstanceConnectionService.ts
  packages/client-core/src/social/services/ChannelService.ts
  packages/client-core/src/transports/SocketWebRTCClientFunctions.ts
  packages/client-core/src/user/components/UserMenu/menus/FriendsMenu.tsx
  packages/client-core/src/user/components/UserMenu/menus/MessagesMenu.tsx
  packages/common/src/dbmodels/UserInterface.ts
  packages/engine/src/networking/NetworkState.ts
  packages/engine/src/networking/systems/MediasoupMediaProducerConsumerState.tsx
  packages/engine/src/schemas/interfaces/Channel.ts
  packages/engine/src/schemas/networking/instance.schema.ts
  packages/engine/src/schemas/social/channel-user.schema.ts
  packages/engine/src/schemas/social/channel.schema.ts
  packages/engine/src/schemas/social/message.schema.ts
  packages/instanceserver/src/channels.ts
  packages/server-core/src/cluster/pods/pods-helper.ts
  packages/server-core/src/hooks/channel-permission-authenticate.ts
  packages/server-core/src/hooks/send-invite.ts
  packages/server-core/src/networking/instance-provision/instance-provision.class.ts
  packages/server-core/src/networking/instance/instance.ts
  packages/server-core/src/social/channel-user/channel-user.hooks.ts
  packages/server-core/src/social/channel-user/channel-user.test.ts
  packages/server-core/src/social/channel/channel.class.ts
  packages/server-core/src/social/channel/channel.docs.ts
  packages/server-core/src/social/channel/channel.hooks.ts
  packages/server-core/src/social/channel/channel.model.ts
  packages/server-core/src/social/channel/channel.resolvers.ts
  packages/server-core/src/social/channel/channel.test.ts
  packages/server-core/src/social/channel/channel.ts
  packages/server-core/src/social/channel/migrations/20230906111413_channel.ts
  packages/server-core/src/social/invite/invite.resolvers.ts
  packages/server-core/src/social/message/message.class.ts
  packages/server-core/src/social/services.ts
  packages/server-core/src/user/accept-invite/accept-invite.class.ts
  packages/taskserver/src/collect-analytics.ts
  packages/ui/src/components/Chat/ChannelsList.tsx
  packages/ui/src/components/Chat/ChatState.ts
  packages/ui/src/components/Chat/Message.tsx
Labels: verified-contributor

#8833 Replace studio scene loading popup with text
  packages/editor/src/components/EditorContainer.tsx
Labels: verified-contributor

#8864 Add Backwards Compatibility for Old EEMaterials
  packages/engine/src/assets/exporters/gltf/extensions/EEMaterialExporterExtension.ts
  packages/engine/src/assets/loaders/gltf/extensions/EEMaterialImporterExtension.ts
Labels: verified-contributor

#8870 Optimize portal data fetching to speed up scene loading
  packages/common/src/interfaces/PortalInterface.ts
  packages/engine/src/scene/components/PortalComponent.ts
  packages/server-core/src/projects/scene/scene-helper.ts
Labels: verified-contributor

#8831 Move scale animation to it's own component, improve spatial input heuristics
  packages/engine/src/input/components/InputComponent.ts
  packages/engine/src/input/systems/ClientInputSystem.ts
  packages/engine/src/renderer/components/AnimateScaleComponent.ts
  packages/engine/src/renderer/components/HighlightComponent.ts
  packages/engine/src/scene/components/LinkComponent.ts
  packages/engine/src/xrui/functions/createXRUI.tsx
Labels: verified-contributor

#8856 refactor(instance): use feathers hooks
  packages/client-core/src/common/services/InstanceService.ts
  packages/client-core/src/user/components/UserMenu/menus/RoomMenu.tsx
Labels: verified-contributor

#8857 refactor(app service): remove action receptors
  packages/client-core/src/common/services/AppService.ts
  packages/client-core/src/components/ARPlacement/index.tsx
  packages/client-core/src/components/InstanceChat/index.tsx
  packages/client-core/src/components/Shelves/index.tsx
Labels: verified-contributor

#8867 fix ios audio
  packages/engine/src/scene/components/MediaComponent.ts
Labels: verified-contributor

#8858 refactor(routerservice): remove arbitary service
  packages/client-core/src/common/services/RouterService.ts
  packages/client-core/src/components/World/EngineHooks.tsx
  packages/client-core/src/components/World/LoadLocationScene.tsx
  packages/client-core/src/user/components/UserMenu/menus/RoomMenu.tsx
  packages/client/src/pages/editor/editor.tsx
  packages/editor/src/components/EditorContainer.tsx
  packages/editor/src/components/assets/ScenesPanel.tsx
  packages/editor/src/components/projects/ProjectsPage.tsx
  packages/engine/src/assets/exporters/gltf/extensions/EEMaterialExporterExtension.ts
Labels: verified-contributor

#8859 refactor(appthemestate): remove action receptor
  packages/client-core/src/common/services/AppThemeState.ts
  packages/client/src/themes/themeContext.tsx
Labels: verified-contributor

#8877 Changes for project seeds to work with knex seed file.
  packages/common/src/interfaces/ServicesSeedConfig.ts
  packages/projects/ProjectConfigInterface.ts
  packages/server-core/src/media/seeder-config.ts
  packages/server-core/src/networking/seeder-config.ts
  packages/server-core/src/seeder-config.ts
  packages/server-core/src/seeder.ts
Labels: verified-contributor

#8753 Load Volume Component
  packages/editor/src/components/element/ElementList.tsx
  packages/editor/src/components/properties/ColliderNodeEditor.tsx
  packages/editor/src/components/properties/LoadVolumeNodeEditor.tsx
  packages/editor/src/functions/ComponentEditors.tsx
  packages/engine/src/scene/components/ColliderComponent.ts
  packages/engine/src/scene/components/LoadVolumeComponent.ts
  packages/engine/src/scene/systems/TriggerSystem.ts
Labels: verified-contributor

#8884 fix skybox
  packages/engine/src/scene/components/EnvmapComponent.tsx
  packages/engine/src/scene/components/SkyboxComponent.ts
  packages/engine/src/scene/constants/Util.ts
Labels: verified-contributor

#8885 Tmobile audiofix
  packages/client-core/src/components/UserMediaWindow/index.tsx
  packages/engine/src/audio/systems/MediaSystem.ts
  packages/engine/src/scene/components/MediaComponent.ts
  packages/engine/src/scene/components/VolumetricComponent.ts
Labels: verified-contributor

#8869 introduced a state concept for asset loader and migrated gltfloader t…
  packages/engine/src/assets/classes/AssetLoader.ts
  packages/engine/src/assets/state/AssetLoaderState.ts
  packages/engine/src/avatar/functions/avatarFunctions.test.ts
  packages/engine/src/ecs/classes/Engine.ts
  packages/engine/src/scene/systems/SceneObjectSystem.tsx
Labels: verified-contributor

#8881 introduced PortalState
  packages/client-core/src/components/World/EngineHooks.tsx
  packages/engine/src/ecs/classes/Engine.ts
  packages/engine/src/scene/components/PortalComponent.ts
  packages/engine/src/scene/functions/loaders/PortalFunctions.ts
  packages/engine/src/scene/systems/HyperspacePortalSystem.ts
Labels: verified-contributor

#8879 Fixed bugs in updateBuilder()
  packages/server-core/src/projects/project/project-helper.ts
Labels: verified-contributor

#8843 fix(admin): instance id being sent in location
  packages/client-core/src/admin/components/Invite/AdminInvites.tsx
  packages/client-core/src/admin/components/Invite/CreateInviteModal.tsx
Labels: verified-contributor

#8854 stop behave graph playing studio
  packages/engine/src/behave-graph/systems/BehaveGraphSystem.ts
Labels: verified-contributor

#8878 fix thumbnails
  packages/editor/src/components/materials/MaterialEditor.tsx
Labels: verified-contributor

#8874 Transform system fixes
  packages/client-core/i18n/en/editor.json
  packages/client-core/src/systems/WidgetUISystem.ts
  packages/editor/src/components/properties/PrefabNodeEditor.tsx
  packages/editor/src/functions/ComponentEditors.tsx
  packages/editor/src/functions/addMediaNode.ts
  packages/editor/src/functions/assetFunctions.ts
  packages/editor/src/functions/takeScreenshot.ts
  packages/engine/src/avatar/systems/AvatarTeleportSystem.ts
  packages/engine/src/behave-graph/nodes/Profiles/Engine/helper/assetHelper.ts
  packages/engine/src/camera/systems/CameraFadeBlackEffectSystem.ts
  packages/engine/src/ecs/functions/EntityTree.ts
  packages/engine/src/initializeEngine.ts
  packages/engine/src/interaction/systems/GrabbableSystem.test.ts
  packages/engine/src/networking/serialization/DataReader.test.ts
  packages/engine/src/networking/serialization/DataWriter.test.ts
  packages/engine/src/physics/classes/Physics.test.ts
  packages/engine/src/physics/functions/physicsObjectDebugFunctions.ts
  packages/engine/src/scene/SceneClientModule.ts
  packages/engine/src/scene/components/GroupComponent.tsx
  packages/engine/src/scene/components/PrefabComponent.ts
  packages/engine/src/scene/functions/loadGLTFModel.test.ts
  packages/engine/src/scene/functions/loadGLTFModel.ts
  packages/engine/src/scene/functions/loaders/PrefabComponentFunctions.test.ts
  packages/engine/src/scene/functions/loaders/PrefabComponentFunctions.ts
  packages/engine/src/scene/functions/serializeWorld.ts
  packages/engine/src/scene/systems/SceneLoadingSystem.tsx
  packages/engine/src/scene/systems/SceneObjectDynamicLoadSystem.ts
  packages/engine/src/transform/components/TransformComponent.ts
  packages/engine/src/transform/systems/TransformSystem.ts
  packages/engine/src/xr/XRAnchorComponents.ts
  packages/engine/src/xr/XRAnchorSystem.ts
  packages/engine/src/xr/XRDetectedPlanesSystem.ts
  packages/engine/src/xrui/functions/createXRUI.tsx
  packages/engine/tests/SoA.test.ts
Labels: verified-contributor

#8890 fix file panel css by making file-browser-panel cover all vertical area
  packages/editor/src/components/assets/FileBrowserContentPanel.tsx
Labels: verified-contributor

#8886 fix head decap not working for invalid avatars
  packages/engine/src/avatar/components/AvatarIKComponents.ts
Labels: verified-contributor

#8888 Fix docs action for clearing commit history before pushing docs changes
  .github/workflows/documentation.yml
Labels: verified-contributor

#8897 Fixed issue with spaces in scene names
  packages/server-core/src/media/storageprovider/s3.storage.ts
  packages/server-core/src/projects/scene/scene.class.ts
Labels: verified-contributor

#8901 Add workflow scope to GitHub oauth seed
  packages/server-core/src/setting/authentication-setting/authentication-setting.seed.ts
Labels: verified-contributor

#8900 Mocap fixes
  packages/engine/src/mocap/MotionCaptureSystem.ts
  packages/engine/src/networking/systems/MediasoupMediaProducerConsumerState.tsx
  packages/instanceserver/src/ServerHostNetworkSystem.tsx
  packages/ui/src/pages/Capture/index.tsx
Labels: verified-contributor

#8903 Clean up consumer pause
  packages/client-core/src/transports/SocketWebRTCClientFunctions.ts
  packages/engine/src/networking/systems/MediasoupMediaProducerConsumerState.tsx
Labels: verified-contributor

#8889 Changes to cleanup feathers underscore methods in adapter based services
  packages/server-core/src/bot/bot/bot.resolvers.ts
  packages/server-core/src/projects/scene/scene.service.ts
  packages/server-core/src/social/location/location.class.ts
  packages/server-core/src/user/user-setting/user-setting.hooks.ts
  packages/server-core/src/user/user/user.ts
Labels: verified-contributor

#8902 8873 Fix saving scene with ktx2 image
  packages/engine/src/assets/loaders/gltf/KTX2Loader.js
  packages/server-core/src/media/file-browser/file-browser.class.ts
  packages/server-core/src/media/static-resource/static-resource-helper.ts
Labels: verified-contributor

#8872 Fixed billing error in stripe-webhook service
  packages/server-core/src/createApp.ts
Labels: verified-contributor

#8914 Fixed issues with static resource hash generation and ktx2 size fetching
  packages/common/src/utils/CommonKnownContentTypes.ts
  packages/instanceserver/src/MediasoupRecordingFunctions.ts
  packages/instanceserver/src/ServerHostNetworkSystem.tsx
  packages/server-core/src/media/file-browser/file-browser.class.ts
  packages/server-core/src/media/static-resource/static-resource-helper.ts
  packages/server-core/src/media/upload-asset/upload-asset.service.ts
  packages/server-core/src/media/upload-asset/upload-asset.test.ts
Labels: verified-contributor

#8913 reset functionality for media
  packages/client-core/i18n/en/editor.json
  packages/editor/src/components/inputs/ArrayInputGroup.tsx
  packages/editor/src/components/properties/MediaNodeEditor.tsx
  packages/engine/src/behave-graph/nodes/Profiles/Engine/Values/CustomNodes.ts
  packages/engine/src/scene/components/MediaComponent.ts
Labels: verified-contributor

#8922 fix selecting non scene entities crashing studio
  packages/editor/src/systems/EditorControlSystem.tsx
Labels: verified-contributor

#8909 fix: Mediacomponent loop
  packages/engine/src/scene/components/MediaComponent.ts
  packages/engine/src/scene/components/VolumetricComponent.ts
Labels: verified-contributor

#8916 Fix Dynamic Bounding Boxes
  packages/engine/src/interaction/components/BoundingBoxComponents.ts
  packages/engine/src/physics/components/RigidBodyComponent.ts
  packages/engine/src/scene/functions/serializeWorld.ts
  packages/engine/src/transform/systems/TransformSystem.ts
Labels: verified-contributor

#8917 Add Priority Queue for Drop Shadows
  packages/engine/src/avatar/systems/AvatarAnimationSystem.ts
  packages/engine/src/ecs/PriorityQueue.ts
  packages/engine/src/scene/systems/ShadowSystem.tsx
Labels: verified-contributor

#8923 Fix Scene Preview Camera Position Race Condition in Studio
  packages/engine/src/scene/components/ScenePreviewCamera.ts
Labels: verified-contributor

#8927 Replace cyberbots with human avatars
  packages/projects/default-project/assets/avatars/CyberbotBlack.png
  packages/projects/default-project/assets/avatars/CyberbotBlack.vrm
  packages/projects/default-project/assets/avatars/CyberbotBlue.png
  packages/projects/default-project/assets/avatars/CyberbotBlue.vrm
  packages/projects/default-project/assets/avatars/CyberbotCyan.png
  packages/projects/default-project/assets/avatars/CyberbotCyan.vrm
  packages/projects/default-project/assets/avatars/CyberbotGold.png
  packages/projects/default-project/assets/avatars/CyberbotGold.vrm
  packages/projects/default-project/assets/avatars/CyberbotGreen.png
  packages/projects/default-project/assets/avatars/CyberbotGreen.vrm
  packages/projects/default-project/assets/avatars/CyberbotPink.png
  packages/projects/default-project/assets/avatars/CyberbotPink.vrm
  packages/projects/default-project/assets/avatars/CyberbotPurple.png
  packages/projects/default-project/assets/avatars/CyberbotPurple.vrm
  packages/projects/default-project/assets/avatars/CyberbotRed.png
  packages/projects/default-project/assets/avatars/CyberbotRed.vrm
  packages/projects/default-project/assets/avatars/CyberbotSilver.png
  packages/projects/default-project/assets/avatars/CyberbotSilver.vrm
  packages/projects/default-project/assets/avatars/CyberbotYellow.png
  packages/projects/default-project/assets/avatars/CyberbotYellow.vrm
  packages/projects/default-project/assets/avatars/female_01.png
  packages/projects/default-project/assets/avatars/female_01.vrm
  packages/projects/default-project/assets/avatars/female_02.png
  packages/projects/default-project/assets/avatars/female_02.vrm
  packages/projects/default-project/assets/avatars/female_03.png
  packages/projects/default-project/assets/avatars/female_03.vrm
  packages/projects/default-project/assets/avatars/male_01.png
  packages/projects/default-project/assets/avatars/male_01.vrm
  packages/projects/default-project/assets/avatars/male_02.png
  packages/projects/default-project/assets/avatars/male_02.vrm
  packages/projects/default-project/assets/avatars/male_03.png
  packages/projects/default-project/assets/avatars/male_03.vrm
Labels: verified-contributor

#8921 reintegrate tracking space scaling
  packages/engine/src/avatar/systems/AvatarAnimationSystem.ts
  packages/engine/src/avatar/systems/AvatarIKTargetSystem.ts
  packages/engine/src/xr/XRScaleAdjustmentFunctions.ts
  packages/engine/src/xr/XRSessionFunctions.ts
  packages/engine/src/xr/XRState.ts
Labels: verified-contributor

#8734 Improve envmap state handling and give avatars Envmap Component
  packages/engine/src/avatar/functions/spawnAvatarReceptor.ts
  packages/engine/src/scene/classes/Sky.ts
  packages/engine/src/scene/components/EnvmapComponent.tsx
  packages/engine/src/scene/components/SkyboxComponent.ts
  packages/engine/src/scene/constants/Util.ts
  packages/engine/src/scene/systems/EnvironmentSystem.ts
  packages/engine/src/scene/systems/SceneObjectSystem.tsx
Labels: verified-contributor

#8919 GLTF Export on Deployment
  packages/editor/src/components/materials/MaterialLibraryEntry.tsx
  packages/editor/src/functions/exportGLTF.ts
  packages/engine/src/assets/exporters/gltf/extensions/URLResolutionExtension.ts
  packages/engine/src/assets/functions/pathResolver.ts
Labels: verified-contributor

#8926 fix single mode & improve invalid path handling
  packages/client-core/i18n/en/editor.json
  packages/editor/src/components/properties/MediaNodeEditor.tsx
  packages/engine/src/scene/components/MediaComponent.ts
Labels: verified-contributor

#8940 Fix scene saving
  packages/editor/src/functions/EditorControlFunctions.ts
Labels: verified-contributor

#8863 8777 Cleanup hookstate usage around components
  packages/engine/src/ecs/classes/Engine.ts
  packages/engine/src/ecs/functions/ComponentFunctions.ts
  packages/engine/src/ecs/functions/EngineFunctions.ts
  packages/engine/src/ecs/functions/EntityFunctions.tsx
  packages/engine/src/ecs/functions/EntityTree.ts
  packages/engine/src/scene/components/UUIDComponent.ts
  packages/engine/tests/ecs/ecs.test.ts
Labels: verified-contributor

#8951 Loading-screen-improvements
  packages/client-core/src/systems/LoadingUISystem.tsx
  packages/client-core/src/systems/ui/LoadingDetailView/index.tsx
  packages/editor/src/components/properties/EnvMapBakeNodeEditor.tsx
  packages/editor/src/functions/uploadEnvMapBake.ts
  packages/engine/src/assets/functions/createReadableTexture.ts
  packages/engine/src/scene/classes/CubemapCapturer.ts
  packages/engine/src/scene/classes/ImageUtils.ts
  packages/engine/src/scene/components/EnvMapBakeComponent.ts
  packages/projects/default-project/apartment.envmap.ktx2
  packages/projects/default-project/apartment.scene.json
  packages/projects/default-project/apartment.thumbnail.ktx2
  packages/projects/default-project/default.envmap.ktx2
  packages/projects/default-project/default.scene.json
  packages/projects/default-project/default.thumbnail.ktx2
  packages/projects/default-project/sky-station.envmap.ktx2
  packages/projects/default-project/sky-station.scene.json
  packages/projects/default-project/sky-station.thumbnail.ktx2
  packages/xrui/core/textures/KTX2Worker.bundle.js
  packages/xrui/core/textures/KTX2Worker.ts
  packages/xrui/core/three/WebLayer3D.ts
Labels: verified-contributor
