Repository EtherealEngine/etherealengine, pull requests merged in 2024-05, with the labels that each got.

#10117 Fix interactable cursor style reactor
  packages/engine/src/interaction/components/InteractableComponent.ts
  packages/engine/src/interaction/systems/InteractableSystem.ts
Labels: verified-contributor

#10092 Fixed setup helm in dev-deploy
  .github/workflows/dev-deploy.yml
  scripts/setup_helm_builder.sh
Labels: verified-contributor

#10118 updated the avatar radius and camera rotation
  packages/engine/src/avatar/components/AvatarControllerComponent.ts
  packages/engine/src/avatar/functions/spawnAvatarReceptor.ts
  packages/engine/src/avatar/systems/AvatarTransparencySystem.ts
  packages/spatial/src/camera/systems/CameraSystem.tsx
Labels: verified-contributor

#10120 IR-1871 SystemDebug System tree systems without any pre/post/sub systems will no longer start out expanded
  packages/client-core/src/components/Debug/SystemDebug.tsx
Labels: verified-contributor

#10102 GLTF ECS Loader
  packages/client-core/i18n/en/editor.json
  packages/client-core/src/components/World/EngineHooks.tsx
  packages/client-core/src/components/World/LoadLocationScene.tsx
  packages/client-core/src/networking/AvatarSpawnSystem.tsx
  packages/client-core/src/social/services/LocationService.ts
  packages/client-core/src/systems/LoadingUISystem.tsx
  packages/client-core/src/world/Location.tsx
  packages/client-core/src/world/SceneServices.ts
  packages/ecs/src/UUIDComponent.ts
  packages/editor/src/components/EditorContainer.tsx
  packages/editor/src/components/hierarchy/HierarchyPanelContainer.tsx
  packages/editor/src/components/hierarchy/HierarchyTreeNode.tsx
  packages/editor/src/functions/EditorControlFunctions.test.tsx
  packages/editor/src/functions/EditorControlFunctions.ts
  packages/editor/src/functions/sceneFunctions.tsx
  packages/engine/src/assets/exporters/gltf/extensions/IgnoreGeometryExporterExtension.ts
  packages/engine/src/assets/functions/resourceHooks.ts
  packages/engine/src/assets/loaders/gltf/GLTFLoader.ts
  packages/engine/src/gltf/GLTFComponent.tsx
  packages/engine/src/gltf/GLTFDocumentState.ts
  packages/engine/src/gltf/GLTFState.tsx
  packages/engine/src/gltf/ResourcePendingComponent.ts
  packages/engine/src/gltf/convertJsonToGLTF.ts
  packages/engine/src/scene/GLTFState.tsx
  packages/engine/src/scene/SceneState.tsx
  packages/engine/src/scene/components/ColliderComponent.ts
  packages/engine/src/scene/components/EnvmapComponent.tsx
  packages/engine/src/scene/components/GroundPlaneComponent.ts
  packages/engine/src/scene/components/ImageComponent.ts
  packages/engine/src/scene/components/ModelComponent.tsx
  packages/engine/src/scene/components/ObjectGridSnapComponent.ts
  packages/engine/src/scene/components/SceneAssetPendingTagComponent.ts
  packages/engine/src/scene/functions/loadGLTFModel.ts
  packages/engine/src/scene/systems/SceneLoadingSystem.test.tsx
  packages/engine/src/scene/systems/SceneLoadingSystem.tsx
  packages/hyperflux/tests/ReactorFunctions.test.tsx
  packages/hyperflux/tests/hookstate.test.tsx
  packages/instanceserver/src/channels.ts
  packages/instanceserver/tests/InstanceLoad.test.ts
  packages/projects/default-project/apartment.gltf
  packages/projects/default-project/apartment.scene.json
  packages/projects/default-project/default.gltf
  packages/projects/default-project/default.scene.json
  packages/projects/default-project/projectEventHooks.ts
  packages/projects/default-project/sky-station.gltf
  packages/projects/default-project/sky-station.scene.json
  packages/server-core/src/assets/asset/asset.hooks.ts
  packages/server-core/src/assets/asset/asset.test.ts
  packages/server-core/src/media/static-resource/static-resource-helper.test.ts
  packages/server-core/src/media/upload-asset/upload-asset.test.ts
  packages/spatial/src/camera/systems/CameraOrbitSystem.tsx
  packages/spatial/src/initializeEngine.ts
  packages/spatial/src/renderer/components/DirectionalLightComponent.ts
  packages/spatial/src/transform/components/EntityTree.tsx
  packages/ui/src/pages/Capture/index.tsx
Labels: verified-contributor

#10122 Remove old ColliderComponent
  packages/engine/src/scene/components/ColliderComponent.ts
  packages/engine/src/scene/functions/migrateOldColliders.ts
Labels: verified-contributor

#10126 Fix scenestate references in playmode tool
  packages/editor/src/components/toolbar/tools/PlayModeTool.tsx
Labels: verified-contributor

#10109 IR 465 ECS Materials
  packages/client-core/i18n/en/editor.json
  packages/editor/src/components/assets/AssetPreviewPanels/MaterialPreviewPanel.tsx
  packages/editor/src/components/element/PropertiesPanelContainer.tsx
  packages/editor/src/components/inputs/ParameterInput.tsx
  packages/editor/src/components/materials/MaterialEditor.tsx
  packages/editor/src/components/materials/MaterialLibraryEntry.tsx
  packages/editor/src/components/materials/MaterialLibraryPanel.tsx
  packages/editor/src/components/materials/MaterialLibraryPanelContainer.tsx
  packages/editor/src/components/properties/MeshNodeEditor.tsx
  packages/editor/src/components/properties/ModelTransformProperties.tsx
  packages/editor/src/functions/EditorControlFunctions.ts
  packages/editor/src/functions/addMediaNode.ts
  packages/engine/src/assets/classes/AssetLoader.ts
  packages/engine/src/assets/exporters/gltf/extensions/EEMaterialExporterExtension.ts
  packages/engine/src/assets/exporters/gltf/extensions/ImageRoutingExtension.ts
  packages/engine/src/assets/functions/createGLTFLoader.ts
  packages/engine/src/assets/functions/exportMaterialsGLTF.ts
  packages/engine/src/assets/loaders/gltf/extensions/EEMaterialImporterExtension.ts
  packages/engine/src/assets/loaders/gltf/extensions/RegisterMaterialsExtension.ts
  packages/engine/src/assets/state/ResourceState.ts
  packages/engine/src/avatar/components/AvatarDissolveComponent.ts
  packages/engine/src/avatar/components/TransparencyDitheringComponent.tsx
  packages/engine/src/avatar/systems/TransparencyDitheringSystem.tsx
  packages/engine/src/scene/SceneModule.ts
  packages/engine/src/scene/components/EnvMapBakeComponent.ts
  packages/engine/src/scene/functions/loadGLTFModel.ts
  packages/engine/src/scene/materials/MaterialLibrary.ts
  packages/engine/src/scene/materials/MaterialLibraryState.ts
  packages/engine/src/scene/materials/components/MaterialComponent.ts
  packages/engine/src/scene/materials/constants/LibraryEntry.ts
  packages/engine/src/scene/materials/constants/material-prototypes/MeshLambertMaterial.mat.ts
  packages/engine/src/scene/materials/constants/material-prototypes/MeshToonMaterial.mat.ts
  packages/engine/src/scene/materials/constants/material-prototypes/ShadowMaterial.mat.ts
  packages/engine/src/scene/materials/constants/plugins/NoiseOffsetPlugin.ts
  packages/engine/src/scene/materials/functions/MaterialFunctions.ts
  packages/engine/src/scene/materials/functions/MaterialLibraryFunctions.ts
  packages/engine/src/scene/materials/functions/MaterialPluginFunctions.ts
  packages/engine/src/scene/materials/functions/bakeToVertices.ts
  packages/engine/src/scene/materials/functions/materialSourcingFunctions.ts
  packages/engine/src/scene/materials/systems/MaterialLibrarySystem.tsx
  packages/engine/src/scene/systems/SceneObjectSystem.tsx
  packages/spatial/src/common/functions/OnBeforeCompilePlugin.ts
  packages/spatial/src/renderer/components/GroupComponent.tsx
  packages/spatial/src/renderer/materials/MaterialComponent.ts
  packages/spatial/src/renderer/materials/constants/BaseMaterials.ts
  packages/spatial/src/renderer/materials/constants/BasicArgs.ts
  packages/spatial/src/renderer/materials/constants/DefaultArgs.ts
  packages/spatial/src/renderer/materials/constants/plugins/NoiseOffsetPlugin.ts
  packages/spatial/src/renderer/materials/materialFunctions.ts
  packages/spatial/src/renderer/materials/prototypes/MeshBasicMaterial.mat.ts
  packages/spatial/src/renderer/materials/prototypes/MeshLambertMaterial.mat.ts
  packages/spatial/src/renderer/materials/prototypes/MeshMatcapMaterial.mat.ts
  packages/spatial/src/renderer/materials/prototypes/MeshPhongMaterial.mat.ts
  packages/spatial/src/renderer/materials/prototypes/MeshPhysicalMaterial.mat.ts
  packages/spatial/src/renderer/materials/prototypes/MeshStandardMaterial.mat.ts
  packages/spatial/src/renderer/materials/prototypes/MeshToonMaterial.mat.ts
  packages/spatial/src/renderer/materials/prototypes/ShaderMaterial.mat.ts
  packages/spatial/src/renderer/materials/prototypes/ShadowMaterial.mat.ts
Labels: verified-contributor

#10128 Add locationType menu
  packages/client-core/src/admin/components/locations/AddEditLocationModal.tsx
Labels: verified-contributor

#10129 Location GLTF State Cleanup
  packages/client-core/src/components/World/LoadLocationScene.tsx
  packages/client-core/src/networking/AvatarSpawnSystem.tsx
  packages/client-core/src/social/services/LocationService.ts
  packages/client-core/src/systems/LoadingUISystem.tsx
  packages/client-core/src/world/SceneServices.ts
  packages/engine/src/gltf/GLTFState.tsx
  packages/ui/src/pages/Capture/index.tsx
Labels: verified-contributor

#10130 Camera and Spectation are Event Sourced
  packages/client-core/src/components/MediaIconsBox/index.tsx
  packages/client-core/src/networking/AvatarSpawnSystem.tsx
  packages/common/src/utils/deleteSearchParams.ts
  packages/engine/src/avatar/systems/AvatarAnimationSystem.ts
  packages/spatial/src/camera/CameraState.ts
  packages/spatial/src/camera/components/FollowCameraComponent.ts
  packages/spatial/src/camera/components/SpectatorComponent.ts
  packages/spatial/src/camera/systems/CameraSystem.tsx
  packages/spatial/src/camera/systems/SpectateSystem.tsx
Labels: verified-contributor

#10127 rework scene loaded state usage
  packages/client-core/src/components/ARPlacement/index.tsx
  packages/client-core/src/components/World/EngineHooks.tsx
  packages/client-core/src/systems/LoadingUISystem.tsx
  packages/client-core/src/systems/ui/LoadingDetailView/index.tsx
  packages/editor/src/components/EditorContainer.tsx
  packages/editor/src/components/assets/ScenesPanel.tsx
  packages/editor/src/services/EditorServices.ts
  packages/engine/src/gltf/GLTFDocumentState.ts
  packages/engine/src/gltf/GLTFState.tsx
  packages/engine/src/scene/SceneState.tsx
  packages/engine/src/scene/components/HyperspaceTagComponent.ts
  packages/engine/src/scene/systems/VariantSystem.tsx
  packages/engine/src/visualscript/components/VisualScriptComponent.tsx
  packages/engine/src/visualscript/systems/VisualScriptSystem.ts
  packages/instanceserver/src/channels.ts
  packages/ui/src/pages/Capture/index.stories.tsx
  packages/ui/src/pages/Chat/chat.tsx
Labels: verified-contributor

#10124 Physics API Abstraction
  packages/engine/src/avatar/components/AvatarControllerComponent.ts
  packages/engine/src/avatar/functions/autopilotFunctions.ts
  packages/engine/src/avatar/functions/avatarFunctions.ts
  packages/engine/src/avatar/functions/moveAvatar.ts
  packages/engine/src/avatar/functions/spawnAvatarReceptor.ts
  packages/engine/src/avatar/systems/AvatarAnimationSystem.ts
  packages/engine/src/gltf/GLTFState.tsx
  packages/engine/src/interaction/systems/GrabbableSystem.tsx
  packages/engine/src/scene/SceneModule.ts
  packages/engine/src/scene/components/MountPointComponent.ts
  packages/engine/src/scene/components/OldColliderComponent.tsx
  packages/engine/src/scene/components/SceneSettingsComponent.ts
  packages/engine/src/scene/functions/migrateOldColliders.ts
  packages/engine/src/scene/systems/SceneKillHeightSystem.tsx
  packages/spatial/src/input/systems/ClientInputSystem.tsx
  packages/spatial/src/physics/PhysicsSerialization.ts
  packages/spatial/src/physics/classes/Physics.test.ts
  packages/spatial/src/physics/classes/Physics.ts
  packages/spatial/src/physics/components/ColliderComponent.test.ts
  packages/spatial/src/physics/components/ColliderComponent.tsx
  packages/spatial/src/physics/components/RigidBodyComponent.ts
  packages/spatial/src/physics/functions/getInteractionGroups.ts
  packages/spatial/src/physics/systems/PhysicsPreTransformSystem.ts
  packages/spatial/src/physics/systems/PhysicsSystem.ts
Labels: verified-contributor

#10125 IR-1831: Add unique constraint to project name column
  packages/server-core/src/projects/project/migrations/20240503102512_project-name-column-unique.ts
Labels: verified-contributor

#10116 fix admin projects and build status modals and statuses
  packages/client-core/src/admin/components/project/AddEditProjectModal.tsx
  packages/client-core/src/admin/components/project/ProjectTable.tsx
  packages/client-core/src/admin/components/project/ProjectTopMenu.tsx
  packages/client-core/src/admin/components/project/UpdateEngineModal.tsx
  packages/client-core/src/admin/components/project/index.tsx
  packages/server-core/src/projects/project/project-helper.ts
Labels: verified-contributor

#10132 Fix dithering uniform references
  packages/engine/src/avatar/systems/TransparencyDitheringSystem.tsx
Labels: verified-contributor

#10133 GLTF editor control function bug fixes
  packages/editor/src/functions/EditorControlFunctions.ts
  packages/engine/package.json
  packages/engine/src/gltf/GLTFState.tsx
Labels: verified-contributor

#10119 IR-1820 playmode interactables
  packages/client-core/src/common/components/TouchGamepad/index.tsx
  packages/client-core/src/systems/LoadingUISystem.tsx
  packages/client-core/src/systems/WarningUISystem.tsx
  packages/client-core/src/systems/WidgetUISystem.ts
  packages/editor/src/components/toolbar/tools/PlayModeTool.tsx
  packages/engine/src/avatar/components/AvatarAnimationComponent.ts
  packages/engine/src/interaction/components/InteractableComponent.ts
  packages/engine/src/interaction/functions/interactableFunctions.ts
  packages/engine/src/interaction/systems/GrabbableSystem.tsx
  packages/engine/src/interaction/systems/InteractableSystem.ts
  packages/engine/src/interaction/systems/MountPointSystem.ts
  packages/spatial/src/camera/components/FollowCameraComponent.ts
  packages/spatial/src/camera/systems/CameraFadeBlackEffectSystem.ts
  packages/spatial/src/camera/systems/CameraOrbitSystem.tsx
  packages/spatial/src/camera/systems/CameraSystem.tsx
  packages/spatial/src/camera/systems/SpectateSystem.tsx
  packages/spatial/src/input/components/InputSourceComponent.tsx
  packages/spatial/src/input/systems/ClientInputSystem.tsx
  packages/spatial/src/transform/components/ComputedTransformComponent.ts
  packages/spatial/src/transform/systems/TransformSystem.ts
  packages/ui/src/pages/Capture/index.tsx
Labels: verified-contributor

#10140 Fix for 403 error in GLTF scene files due to private ACL
  packages/common/src/constants/ProjectKeyConstants.ts
  packages/server-core/src/media/storageprovider/s3.storage.ts
  packages/server-core/src/projects/project/downloadProjects.ts
Labels: verified-contributor

#10134 Added fsProjectSyncEnabled
  .env.local.default
  packages/editor/src/components/EditorContainer.tsx
  packages/editor/src/functions/sceneFunctions.tsx
  packages/server-core/src/appconfig.ts
  packages/server-core/src/assets/asset/asset.hooks.ts
  packages/server-core/src/media/file-browser/file-browser.class.ts
  packages/server-core/src/media/upload-asset/upload-asset.service.ts
  packages/server-core/src/projects/project/project-helper.ts
  packages/server-core/src/projects/project/project.class.ts
  packages/server-core/src/projects/project/project.resolvers.ts
  packages/server-core/src/setting/client-setting/client-setting.hooks.ts
  packages/server-core/src/user/avatar/avatar-helper.ts
  packages/server-core/tests/mocha.env.js
Labels: verified-contributor

#10143 Revert change to scene save asset url
  packages/editor/src/functions/sceneFunctions.tsx
Labels: verified-contributor

#10142 Admin search fixes
  packages/client-core/src/admin/components/avatar/AvatarTable.tsx
  packages/client-core/src/admin/components/channel/ChannelTable.tsx
  packages/client-core/src/admin/components/instance/InstanceTable.tsx
  packages/client-core/src/admin/components/instance/ViewModal.tsx
  packages/client-core/src/admin/components/instance/index.tsx
  packages/client-core/src/admin/components/invites/InviteTable.tsx
  packages/client-core/src/admin/components/locations/LocationTable.tsx
  packages/client-core/src/admin/components/recordings/RecordingsTable.tsx
  packages/client-core/src/admin/components/resources/ResourceTable.tsx
  packages/client-core/src/admin/components/user/UserTable.tsx
Labels: verified-contributor

#10137 Refactoring MathConstants.ts Vector3 and folding in Axis3D.ts
  packages/client-core/src/systems/WidgetUISystem.ts
  packages/editor/src/functions/gizmoHelper.ts
  packages/editor/src/systems/EditorControlSystem.tsx
  packages/engine/src/avatar/animation/TwoBoneIKSolver.ts
  packages/engine/src/avatar/components/SpawnEffectComponent.ts
  packages/engine/src/avatar/functions/autopilotFunctions.ts
  packages/engine/src/avatar/functions/avatarFootHeuristics.ts
  packages/engine/src/avatar/functions/moveAvatar.ts
  packages/engine/src/avatar/systems/AvatarInputSystem.ts
  packages/engine/src/interaction/systems/GrabbableSystem.tsx
  packages/engine/src/mocap/solveMotionCapturePose.ts
  packages/engine/src/scene/components/HyperspaceTagComponent.ts
  packages/engine/src/scene/components/PortalComponent.ts
  packages/engine/src/scene/components/SplineComponent.ts
  packages/engine/src/scene/systems/ShadowSystem.tsx
  packages/spatial/src/camera/systems/CameraOrbitSystem.tsx
  packages/spatial/src/common/constants/Axis3D.ts
  packages/spatial/src/common/constants/MathConstants.ts
  packages/spatial/src/input/systems/ClientInputSystem.tsx
  packages/spatial/src/input/systems/FlyControlSystem.ts
  packages/spatial/src/physics/classes/Physics.test.ts
  packages/spatial/src/physics/classes/Physics.ts
  packages/spatial/src/physics/systems/PhysicsPreTransformSystem.ts
  packages/spatial/src/renderer/csm/CSM.ts
  packages/spatial/src/xr/8thwall/XR8WebXRProxy.ts
  packages/spatial/src/xr/XRAnchorSystem.tsx
  packages/spatial/src/xr/XRCameraSystem.ts
  packages/spatial/src/xr/XRLightProbeSystem.ts
  packages/spatial/src/xr/XRSessionFunctions.ts
Labels: verified-contributor

#10131 remove admin old routes
  packages/client/src/main.tsx
  packages/client/src/route/public.tsx
  packages/server-core/src/media/storageprovider/s3.storage.ts
  packages/server-core/src/route/route/route.seed.ts
Labels: verified-contributor

#10135 Fix bugs with avatar hitting trigger and add reactivity for ColliderComponent
  packages/engine/src/avatar/functions/moveAvatar.ts
  packages/spatial/src/physics/classes/Physics.test.ts
  packages/spatial/src/physics/classes/Physics.ts
  packages/spatial/src/physics/components/ColliderComponent.tsx
  packages/spatial/src/physics/types/PhysicsTypes.ts
Labels: verified-contributor

#10146 feat(IR-1829-left-navbar): improvements on Accordion Tailwind component
  packages/ui/src/primitives/tailwind/Accordion/index.tsx
Labels: verified-contributor

#10151 Remove guest identity provider on email login
  packages/server-core/src/user/login/login.class.ts
Labels: verified-contributor

#10152 fix tsc error accordion
  packages/ui/src/primitives/tailwind/Accordion/index.tsx
Labels: verified-contributor

#10153 URI encoding cache invalidation paths
  scripts/run-batch-invalidation.ts
Labels: verified-contributor

#10155 remove raycast console.log in client input system
  packages/spatial/src/input/systems/ClientInputSystem.tsx
Labels: verified-contributor

#10156 Fixed bugs with builder commit fetching
  packages/server-core/src/media/storageprovider/s3.storage.ts
  packages/server-core/src/projects/builder-info/builder-info.class.ts
  packages/server-core/src/projects/project/project-helper.ts
  packages/server/.aws/credentials
Labels: verified-contributor

#10159 Added migration to fix identity-provider token length.
  packages/server-core/src/user/identity-provider/migrations/20240514172212_identity-provider-change-token-length.ts
Labels: verified-contributor

#10136 IR 1900 ECS Plugin Parameters by Shader, Various Bugfixes
  packages/editor/src/components/materials/MaterialEditor.tsx
  packages/editor/src/components/materials/MaterialLibraryEntry.tsx
  packages/editor/src/components/materials/MaterialLibraryPanelContainer.tsx
  packages/editor/src/functions/EditorControlFunctions.ts
  packages/editor/src/functions/addMediaNode.ts
  packages/engine/src/assets/exporters/gltf/extensions/EEMaterialExporterExtension.ts
  packages/engine/src/avatar/components/TransparencyDitheringComponent.tsx
  packages/engine/src/avatar/systems/TransparencyDitheringSystem.tsx
  packages/engine/src/scene/components/EnvMapBakeComponent.ts
  packages/engine/src/scene/components/EnvmapComponent.tsx
  packages/engine/src/scene/materials/functions/materialSourcingFunctions.ts
  packages/engine/src/scene/materials/systems/MaterialLibrarySystem.tsx
  packages/engine/src/scene/systems/SceneObjectSystem.tsx
  packages/spatial/src/common/functions/OnBeforeCompilePlugin.ts
  packages/spatial/src/renderer/materials/MaterialComponent.ts
  packages/spatial/src/renderer/materials/constants/plugins/NoiseOffsetPlugin.ts
  packages/spatial/src/renderer/materials/materialFunctions.ts
Labels: verified-contributor

#10154 show the modal on update project
  packages/client-core/i18n/en/admin.json
  packages/client-core/src/admin/components/project/AddEditProjectModal.tsx
  packages/client-core/src/admin/components/project/ProjectTable.tsx
  packages/client-core/src/admin/components/settings/tabs/project.tsx
Labels: verified-contributor

#10163 Reworked assetURL in saveSceneGLTF
  packages/editor/src/functions/sceneFunctions.tsx
Labels: verified-contributor

#10161 [IR-1828] fix: Reparenting Transform applied based on the new Parent Transform
  packages/editor/src/functions/EditorControlFunctions.ts
Labels: bug, verified-contributor

#10167 IR-2065-fix-Gextension-unmount
  packages/engine/src/gltf/GLTFState.tsx
Labels: verified-contributor

#10168 Remove redundant code for client setting seed
  packages/server-core/src/setting/client-setting/client-setting.seed.ts
Labels: verified-contributor

#10164 fix linkedin icon on user table
  packages/client-core/src/admin/components/user/AccountIdentifiers.tsx
Labels: verified-contributor

#10157 IR-1775-Split-dev-test-suite-into-Examples-Tests-and-Benchmarks
  packages/engine/src/assets/functions/resourceLoaderFunctions.test.tsx
  packages/engine/src/assets/functions/resourceLoaderFunctions.ts
  packages/spatial/src/resources/ResourceState.ts
Labels: verified-contributor

#10172 Updated usage of refreshApiPods
  packages/server-core/src/hooks/refresh-api-pods.ts
  packages/server-core/src/setting/authentication-setting/authentication-setting.hooks.ts
  packages/server-core/src/user/email/email.hooks.ts
Labels: verified-contributor

#10165 Ir 2021 lookdev
  packages/common/src/utils/CommonKnownContentTypes.ts
  packages/common/src/utils/guessContentType.tsx
  packages/editor/src/constants/AssetTypes.ts
  packages/editor/src/functions/EditorControlFunctions.ts
  packages/editor/src/functions/addMediaNode.ts
  packages/engine/src/assets/classes/AssetLoader.ts
  packages/engine/src/assets/enum/AssetClass.ts
Labels: verified-contributor

#10177 IR-2100: Changes to make asset service query able based on feathers
  packages/common/src/schemas/assets/asset.schema.ts
Labels: verified-contributor

#10176 feat(IR-515-project): adding sm size to the toggle tailwind toggle
  packages/ui/src/primitives/tailwind/Toggle/index.tsx
Labels: verified-contributor

#10175 remove QAT workflow, and add IR Engine Dev deploy workflow; IR-146
  .github/workflows/ir-engine-dev-deploy.yml
  .github/workflows/qat-deploy.yml
Labels: verified-contributor

#10182 Fix syncStateWithLocalStorage
  packages/hyperflux/functions/StateFunctions.ts
Labels: verified-contributor

#10183 fixing localStorage plugin
  packages/hyperflux/functions/StateFunctions.ts
Labels: verified-contributor

#10184 migrate default scenes
  packages/server-core/src/assets/asset/migrations/20240517215739_default_project_assets.ts
Labels: verified-contributor

#10181 Hard-coded scopes in linkedin scope migration
  packages/server-core/src/setting/authentication-setting/migrations/20240516222541_change-linkedin-scopes.ts
Labels: verified-contributor

#10187 Update default scene thumbnail URLs in GLTFs
  packages/projects/default-project/public/scenes/apartment.gltf
  packages/projects/default-project/public/scenes/default.gltf
  packages/projects/default-project/public/scenes/sky-station.gltf
Labels: verified-contributor

#10162 Rework GLTF State loader to use a UUID dictionary
  packages/ecs/src/Engine.ts
  packages/editor/src/components/properties/ConvertOldCollider.tsx
  packages/editor/src/functions/EditorControlFunctions.test.tsx
  packages/editor/src/functions/EditorControlFunctions.ts
  packages/editor/src/functions/filterParentEntities.ts
  packages/engine/src/assets/functions/resourceLoaderFunctions.test.tsx
  packages/engine/src/assets/functions/resourceLoaderHooks.test.tsx
  packages/engine/src/gltf/GLTFComponent.tsx
  packages/engine/src/gltf/GLTFDocumentState.ts
  packages/engine/src/gltf/GLTFState.test.tsx
  packages/engine/src/gltf/GLTFState.tsx
  packages/engine/src/scene/components/ModelComponent.tsx
  packages/engine/src/scene/systems/SceneLoadingSystem.test.tsx
  packages/engine/tests/util/loadGLTFAssetNode.ts
  packages/spatial/src/transform/components/EntityTree.tsx
Labels: verified-contributor

#10188 Remove Deprecated Scene State
  packages/client-core/src/components/Debug/EntityDebug.tsx
  packages/editor/src/components/hierarchy/HierarchyPanelContainer.tsx
  packages/editor/src/functions/EditorControlFunctions.ts
  packages/editor/src/functions/SceneSnapshot.test.tsx
  packages/editor/src/systems/EditorControlSystem.tsx
  packages/engine/src/avatar/functions/moveAvatar.test.tsx
  packages/engine/src/avatar/functions/spawnAvatarReceptor.test.tsx
  packages/engine/src/avatar/functions/spawnAvatarReceptor.ts
  packages/engine/src/gltf/GLTFState.test.tsx
  packages/engine/src/gltf/GLTFState.tsx
  packages/engine/src/interaction/systems/GrabbableSystem.test.ts
  packages/engine/src/scene/SceneModule.ts
  packages/engine/src/scene/SceneState.tsx
  packages/engine/src/scene/functions/GLTFConversion.ts
  packages/engine/src/scene/systems/SceneLoadingSystem.test.tsx
  packages/engine/src/scene/systems/SceneLoadingSystem.tsx
  packages/engine/tests/util/loadEmptyScene.ts
Labels: verified-contributor

#10190 Fixed bug in invalidation path encoding
  scripts/run-batch-invalidation.ts
Labels: verified-contributor

#10191 Fix spatial text
  packages/engine/src/scene/components/TextComponent.tsx
Labels: verified-contributor

#10169 Refactor regex patterns for project keys
  packages/common/src/constants/ProjectKeyConstants.ts
  packages/server-core/src/media/storageprovider/s3.storage.ts
  packages/server-core/src/projects/project/downloadProjects.ts
Labels: verified-contributor

#10150 prevent multiple rerender due to materialquery array
  packages/editor/src/components/materials/MaterialLibraryPanelContainer.tsx
Labels: verified-contributor

#10179 studio: text align left for file table
  packages/ui/src/components/editor/panels/Files/browserGrid/index.tsx
Labels: verified-contributor

#10178 studio: update folder icon
  packages/ui/src/components/editor/panels/Files/icon/index.tsx
Labels: verified-contributor

#10197 Fixed a few remaining outdated scene file path references
  packages/projects/default-project/public/scenes/apartment.gltf
  packages/projects/default-project/public/scenes/sky-station.gltf
Labels: verified-contributor

#10200 Fix bug in instanceserver provisioning
  packages/server-core/src/networking/instance-provision/instance-provision.class.ts
Labels: verified-contributor

#10145 fix(ir-engine): fixed corrupted projects due git http connection
  scripts/install-manifest.ts
Labels: bug, verified-contributor, javascript

#10202 fix default project asset migration
  packages/server-core/src/assets/asset/migrations/20240517215739_default_project_assets.ts
Labels: verified-contributor

#10196 studio: highlight selected file view mode
  packages/ui/src/components/editor/panels/Files/container/index.tsx
Labels: verified-contributor

#10203 Static Resources and File Browser Client Services Cleanup
  packages/client-core/src/admin/components/resources/AddEditResourceModal.tsx
  packages/client-core/src/admin/components/resources/ResourceTable.tsx
  packages/client-core/src/admin/services/ResourceService.ts
  packages/client-core/src/common/services/FileBrowserService.ts
  packages/client-core/src/common/services/FileThumbnailJobState.tsx
  packages/common/src/schema.type.module.ts
  packages/common/src/schemas/media/static-resource-filters.schema.ts
  packages/common/src/schemas/media/static-resource-type.schema.ts
  packages/editor/src/components/assets/FileBrowser/FileBrowserContentPanel.tsx
  packages/editor/src/components/assets/FileBrowser/FileBrowserGrid.tsx
  packages/editor/src/components/assets/ModelCompressionPanel.tsx
  packages/editor/src/components/properties/ModelTransformProperties.tsx
  packages/editor/src/functions/assetFunctions.ts
  packages/server-core/src/media/file-browser/file-browser.class.ts
  packages/server-core/src/media/services.ts
  packages/server-core/src/media/static-resource-filters/static-resource-filters.class.ts
  packages/server-core/src/media/static-resource-filters/static-resource-filters.docs.ts
  packages/server-core/src/media/static-resource-filters/static-resource-filters.hooks.ts
  packages/server-core/src/media/static-resource-filters/static-resource-filters.resolvers.ts
  packages/server-core/src/media/static-resource-filters/static-resource-filters.ts
  packages/server-core/src/services.ts
Labels: verified-contributor

#10201 Assets Panel Category Hierarchy
  packages/editor/src/components/assets/AssetsPanelCategories.ts
  packages/editor/src/components/assets/SceneAssetsPanel.tsx
Labels: verified-contributor

#10193 Move physics enter/exit back to reactors
  packages/ecs/src/QueryFunctions.tsx
  packages/spatial/src/physics/classes/Physics.test.ts
  packages/spatial/src/physics/components/ColliderComponent.test.ts
  packages/spatial/src/physics/components/ColliderComponent.tsx
  packages/spatial/src/physics/components/RigidBodyComponent.ts
  packages/spatial/src/physics/components/TriggerComponent.ts
  packages/spatial/src/physics/systems/PhysicsSystem.ts
  packages/spatial/src/renderer/components/SceneComponents.tsx
  packages/spatial/src/transform/components/EntityTree.tsx
Labels: verified-contributor

#10211 [IR-2122] studio: fix unique key warnings
  packages/editor/src/components/assets/ScenesPanel.tsx
  packages/editor/src/components/toolbar/Toolbar2.tsx
  packages/ui/src/components/editor/panels/Scenes/container/index.tsx
Labels: verified-contributor

#10210 [IR-2087] studio: update ContextMenu
  packages/ui/src/components/editor/layout/ContextMenu.tsx
  packages/ui/src/components/editor/layout/Panel.tsx
Labels: verified-contributor

#10207 studio: polish hierarchy menu
  packages/ui/src/components/editor/panels/Hierarchy/container/index.tsx
  packages/ui/src/components/editor/panels/Hierarchy/node/index.tsx
Labels: verified-contributor

#10205 refactor: Update Primus initialization to include pathname in server URL
  packages/client-core/src/API.ts
Labels: verified-contributor

#10206 IR-2018 Refactor the Select component to disable search functionality for the dropdown only
  packages/client-core/src/admin/components/user/AddEditUserModal.tsx
  packages/ui/src/primitives/tailwind/Select/index.tsx
Labels: verified-contributor

#10219 Ir 1652 interactable input refactor
  packages/editor/src/components/properties/InputComponentNodeEditor.tsx
  packages/editor/src/functions/ComponentEditors.tsx
  packages/spatial/src/input/components/InputComponent.ts
  packages/spatial/src/input/components/InputPointerComponent.ts
  packages/spatial/src/input/systems/ClientInputSystem.tsx
Labels: verified-contributor

#10216 Cleaned location hooks
  packages/server-core/src/social/location/location.hooks.ts
  packages/server-core/src/social/location/location.resolvers.ts
  packages/server-core/src/social/location/location.test.ts
Labels: verified-contributor

#10225 Changes for feature flag schema to be string enum
  packages/client-core/src/networking/NetworkInstanceProvisioning.tsx
  packages/client-core/src/user/UserUISystem.tsx
  packages/client-core/src/user/components/UserMenu/menus/AvatarModifyMenu.tsx
  packages/common/src/schemas/setting/feature-flag-setting.schema.ts
  packages/engine/src/FeatureFlagsState.tsx
Labels: verified-contributor

#10204 feat(setup): update logo and components props
  packages/client/public/favicon-16x16.png
  packages/client/public/favicon-32x32.png
  packages/client/scripts/getClientSettings.ts
  packages/ui/src/primitives/tailwind/Accordion/index.tsx
  packages/ui/src/primitives/tailwind/Button/index.tsx
Labels: verified-contributor

#10228 Fix useGet usage w/ query
  packages/spatial/src/common/functions/FeathersHooks.tsx
Labels: verified-contributor

#10223 Made client's server.js not bound to a specific host
  packages/client/server.js
Labels: verified-contributor

#10224 Fixed webcam light not turning off when camera paused.
  packages/client-core/src/components/UserMediaWindow/index.tsx
  packages/client-core/src/transports/SocketWebRTCClientFunctions.ts
Labels: verified-contributor

#10180 IR-2102 Material/Plugin Parameters
  packages/editor/src/components/assets/AssetPreviewPanels/MaterialPreviewPanel.tsx
  packages/editor/src/components/materials/MaterialEditor.tsx
  packages/engine/src/scene/materials/systems/MaterialLibrarySystem.tsx
  packages/spatial/src/camera/systems/CameraOrbitSystem.tsx
  packages/spatial/src/renderer/materials/materialFunctions.ts
Labels: verified-contributor

#10229 query function fix
  packages/ecs/src/QueryFunctions.tsx
Labels: verified-contributor

#10208 IR-1887-Asset-Preview-breaking-if-you-click-gltf-that-is-in-the-scene
  packages/editor/src/functions/EditorControlFunctions.ts
  packages/engine/src/gltf/GLTFState.test.tsx
  packages/engine/src/gltf/GLTFState.tsx
  packages/engine/src/scene/components/ModelComponent.tsx
Labels: verified-contributor

#10230 vrm expressionmanager was being thrown away it is actually needed for…
  packages/engine/src/avatar/functions/avatarFunctions.ts
Labels: verified-contributor

#10231 corrected white wireframe not visible issue
  packages/spatial/src/renderer/WebGLRendererSystem.tsx
  packages/spatial/src/renderer/functions/changeRenderMode.ts
Labels: verified-contributor

#10198 [IR-2123] studio: smaller spinner
  packages/client/src/pages/editor2/index.tsx
  packages/ui/src/components/editor/panels/Files/container/index.tsx
Labels: verified-contributor

#10221 physics bug fix
  packages/engine/src/gltf/GLTFState.tsx
  packages/spatial/src/physics/components/ColliderComponent.tsx
Labels: verified-contributor

#10241 Update tween.js version
  packages/engine/package.json
  packages/spatial/package.json
Labels: verified-contributor

#10236 hotfix vrm0 data not being where we expect it
  packages/engine/src/avatar/functions/avatarFunctions.ts
Labels: verified-contributor

#10222 Dereference prefabs
  packages/editor/src/functions/EditorControlFunctions.ts
  packages/editor/src/functions/addMediaNode.ts
  packages/engine/src/gltf/AuthoringHookState.tsx
  packages/projects/default-project/assets/geo.prefab.gltf
  packages/projects/default-project/assets/pointLight.prefab.gltf
Labels: verified-contributor

#10242 Ir 2114 prefab
  packages/editor/src/components/prefabs/PrefabEditors.tsx
  packages/editor/src/components/prefabs/PrefabList.tsx
  packages/projects/default-project/assets/prefabs/3d-model.prefab.gltf
  packages/projects/default-project/assets/prefabs/ambient-light.prefab.gltf
  packages/projects/default-project/assets/prefabs/box-collider.prefab.gltf
  packages/projects/default-project/assets/prefabs/cylinder-collider.prefab.gltf
  packages/projects/default-project/assets/prefabs/directional-light.prefab.gltf
  packages/projects/default-project/assets/prefabs/fog.prefab.gltf
  packages/projects/default-project/assets/prefabs/geo.prefab.gltf
  packages/projects/default-project/assets/prefabs/hemisphere-light.prefab.gltf
  packages/projects/default-project/assets/prefabs/mesh-collider.prefab.gltf
  packages/projects/default-project/assets/prefabs/point-light.prefab.gltf
  packages/projects/default-project/assets/prefabs/postprocessing.prefab.gltf
  packages/projects/default-project/assets/prefabs/skybox.prefab.gltf
  packages/projects/default-project/assets/prefabs/sphere-collider.prefab.gltf
  packages/projects/default-project/assets/prefabs/spot-light.prefab.gltf
  packages/projects/default-project/assets/prefabs/text.prefab.gltf
Labels: verified-contributor

#10213 IR-2080 CSM Fixes
  packages/engine/src/scene/systems/ShadowSystem.tsx
  packages/spatial/src/renderer/csm/CSM.ts
  packages/spatial/src/transform/components/EntityTree.tsx
Labels: verified-contributor

#10239 tailwind prettier format
  packages/client-core/src/admin/adminRoutes.tsx
  packages/client-core/src/admin/components/project/UpdateEngineModal.tsx
  packages/client-core/src/admin/components/settings/tabs/authentication.tsx
  packages/client-core/src/admin/components/settings/tabs/aws.tsx
  packages/client-core/src/admin/components/settings/tabs/client.tsx
  packages/client-core/src/admin/components/settings/tabs/email.tsx
  packages/client-core/src/admin/components/settings/tabs/helm.tsx
  packages/client-core/src/admin/components/settings/tabs/project.tsx
  packages/client-core/src/admin/components/settings/tabs/server.tsx
  packages/ui/src/primitives/tailwind/MultiEmailInput/index.tsx
  packages/ui/src/primitives/tailwind/MultiSelect/index.tsx
  packages/ui/src/primitives/tailwind/Radio/index.tsx
  packages/ui/src/primitives/tailwind/Select/index.tsx
  packages/ui/src/primitives/tailwind/Tabs/index.tsx
Labels: verified-contributor

#10237 remove duplicate tailwind config and use single config
  packages/client-core/src/admin/adminRoutes.tsx
  packages/client-core/src/admin/components/avatar/AvatarTable.tsx
  packages/client-core/src/admin/components/channel/ChannelTable.tsx
  packages/client-core/src/admin/components/instance/InstanceTable.tsx
  packages/client-core/src/admin/components/invites/InviteTable.tsx
  packages/client-core/src/admin/components/locations/LocationTable.tsx
  packages/client-core/src/admin/components/project/AddEditProjectModal.tsx
  packages/client-core/src/admin/components/project/ProjectTable.tsx
  packages/client-core/src/admin/components/project/UpdateEngineModal.tsx
  packages/client-core/src/admin/components/recordings/RecordingsTable.tsx
  packages/client-core/src/admin/components/resources/ResourceTable.tsx
  packages/client-core/src/admin/components/server/ServerTable.tsx
  packages/client-core/src/admin/components/server/index.tsx
  packages/client-core/src/admin/components/settings/tabs/authentication.tsx
  packages/client-core/src/admin/components/settings/tabs/aws.tsx
  packages/client-core/src/admin/components/settings/tabs/client.tsx
  packages/client-core/src/admin/components/settings/tabs/email.tsx
  packages/client-core/src/admin/components/settings/tabs/helm.tsx
  packages/client-core/src/admin/components/settings/tabs/project.tsx
  packages/client-core/src/admin/components/settings/tabs/server.tsx
  packages/client-core/src/admin/components/user/UserTable.tsx
  packages/client-core/tailwind.config.js
  packages/client/src/pages/_app_tw.tsx
  packages/client/tailwind.config.js
  packages/ui/src/primitives/tailwind/Accordion/index.tsx
  packages/ui/src/primitives/tailwind/Input/index.tsx
  packages/ui/src/primitives/tailwind/Label/index.tsx
  packages/ui/src/primitives/tailwind/Modal/index.tsx
  packages/ui/src/primitives/tailwind/MultiEmailInput/index.tsx
  packages/ui/src/primitives/tailwind/MultiSelect/index.tsx
  packages/ui/src/primitives/tailwind/Progress/index.tsx
  packages/ui/src/primitives/tailwind/Radio/index.tsx
  packages/ui/src/primitives/tailwind/Select/index.tsx
  packages/ui/src/primitives/tailwind/Table/index.tsx
  packages/ui/src/primitives/tailwind/Tabs/index.tsx
  packages/ui/src/primitives/tailwind/Toggle/index.tsx
  tailwind.config.js
Labels: verified-contributor

#10248 fix not uploading existing projects locally
  packages/server-core/src/projects/project/project.class.ts
Labels: verified-contributor

#10238 dynamic studio navigation in project page
  packages/editor/src/components/projects/ProjectsPage.tsx
  packages/editor/src/pages/EditorPage.tsx
  packages/editor/src/pages/ProjectPage.tsx
Labels: verified-contributor

#10250 Fix TextComponent & SpotLightComponent
  packages/engine/src/scene/components/TextComponent.tsx
  packages/spatial/src/renderer/components/SpotLightComponent.ts
Labels: verified-contributor

#10249 Update email text
  packages/server-core/email-templates/account/magiclink-email.pug
Labels: verified-contributor

#10226 Changes to display feature flag in admin panel
  packages/client-core/i18n/en/admin.json
  packages/client-core/src/admin/components/settings/index.tsx
  packages/client-core/src/admin/components/settings/tabs/features.tsx
Labels: verified-contributor

#10258 fix(magic-link): delete previous tokens [IR-2017]
  packages/server-core/src/user/magic-link/magic-link.class.ts
Labels: bug, verified-contributor

#10253 Optimize install projects find query
  scripts/install-projects.js
Labels: verified-contributor

#10262 IR-1986 input raycast changes
  packages/engine/src/scene/components/ModelComponent.tsx
  packages/engine/src/scene/systems/MeshBVHSystem.tsx
  packages/engine/src/scene/systems/SceneObjectSystem.tsx
  packages/spatial/src/input/state/InputState.ts
  packages/spatial/src/input/systems/ClientInputSystem.tsx
Labels: verified-contributor

#10264 Optimize getComponent
  packages/ecs/src/ComponentFunctions.ts
  packages/engine/src/gltf/GLTFState.tsx
Labels: verified-contributor

#10232 [IR-2124] studio: update FilesPanelTab & FileBrowserContentPanel
  packages/client-core/i18n/en/editor.json
  packages/editor/src/components/Editor2Container.css
  packages/editor/src/components/assets/FileBrowser/FileBrowserContentPanel.tsx
  packages/editor/src/components/assets/FileBrowser/FileBrowserGrid.tsx
  packages/ui/src/components/Chat/Create.tsx
  packages/ui/src/components/Chat/Message.tsx
  packages/ui/src/components/editor/input/Image/Preview/index.tsx
  packages/ui/src/components/editor/input/Texture/index.tsx
  packages/ui/src/components/editor/layout/ContextMenu.tsx
  packages/ui/src/components/editor/layout/Panel.tsx
  packages/ui/src/components/editor/panels/Assets/container/index.tsx
  packages/ui/src/components/editor/panels/Files/browserGrid/index.tsx
  packages/ui/src/components/editor/panels/Files/container/index.tsx
  packages/ui/src/components/editor/panels/Files/icon/index.tsx
  packages/ui/src/components/editor/panels/Properties/container/index.tsx
  packages/ui/src/components/editor/panels/Scenes/container/index.tsx
  packages/ui/src/components/editor/panels/preview/material/index.tsx
  packages/ui/src/primitives/tailwind/Tooltip/index.tsx
Labels: verified-contributor

#10268 Move studio registries to appropriate directory
  packages/editor/src/components/element/ElementList.tsx
  packages/editor/src/components/element/PropertiesPanelContainer.tsx
  packages/editor/src/components/hierarchy/HierarchyTreeNode.tsx
  packages/editor/src/services/ComponentEditors.tsx
  packages/editor/src/services/ComponentShelfCategoriesState.ts
  packages/ui/src/components/editor/panels/Hierarchy/node/index.tsx
  packages/ui/src/components/editor/panels/Properties/container/index.tsx
  packages/ui/src/components/editor/panels/Properties/elementList/index.tsx
Labels: verified-contributor

#10266 fix click root scene entity crash
  packages/editor/src/components/element/PropertiesPanelContainer.tsx
  packages/engine/src/gltf/GLTFDocumentState.ts
Labels: verified-contributor

#10265 Improve Interactable XRUI
  packages/client-core/src/components/Debug/EntityDebug.tsx
  packages/common/src/utils/smootheLerpAlpha.ts
  packages/ecs/src/ComponentFunctions.ts
  packages/engine/src/avatar/components/AvatarComponent.ts
  packages/engine/src/avatar/functions/moveAvatar.ts
  packages/engine/src/avatar/systems/AvatarTransparencySystem.ts
  packages/engine/src/interaction/components/InteractableComponent.ts
  packages/engine/src/interaction/functions/createUI.ts
  packages/engine/src/interaction/ui/InteractiveModalView.tsx
  packages/engine/src/scene/systems/MeshBVHSystem.tsx
  packages/spatial/src/camera/components/FollowCameraComponent.ts
  packages/spatial/src/common/functions/MathLerpFunctions.ts
  packages/spatial/src/input/systems/ClientInputSystem.tsx
  packages/spatial/src/physics/systems/PhysicsSystem.ts
  packages/spatial/src/xr/XRAnchorSystem.tsx
Labels: verified-contributor

#10267 Fix infinite loading in `VariantComponent`
  packages/editor/src/components/properties/VariantNodeEditor.tsx
Labels: verified-contributor

#10269 fix(auth): remove previous login tokens [IR-2322]
  packages/server-core/src/user/magic-link/magic-link.class.ts
Labels: bug, verified-contributor

#10273 chore[ee]: improved single-branch cloning feature as optional
  scripts/install-manifest.ts
Labels: verified-contributor

#10276 Clean up unused asset loader functions
  packages/editor/src/components/properties/VariantNodeEditor.tsx
  packages/editor/src/components/properties/three.quarks/BehaviorInput.tsx
  packages/engine/src/assets/classes/AssetLoader.test.ts
  packages/engine/src/assets/classes/AssetLoader.ts
  packages/engine/src/assets/functions/resourceLoaderFunctions.test.tsx
  packages/engine/src/assets/functions/resourceLoaderFunctions.ts
  packages/engine/src/assets/functions/resourceLoaderHooks.ts
  packages/engine/src/assets/state/ResourceLoadingManager.test.tsx
  packages/engine/src/scene/components/ModelComponent.tsx
  packages/engine/src/scene/components/OldColliderComponent.tsx
  packages/engine/src/scene/components/ParticleSystemComponent.ts
  packages/spatial/src/resources/ResourceState.ts
Labels: verified-contributor

#10277 IR-2364 fix material properties not populating
  packages/editor/src/components/element/PropertiesPanelContainer.tsx
Labels: verified-contributor

#10255 IR: 1609: Handle scene renaming with existing scene name
  packages/client-core/i18n/en/editor.json
  packages/editor/src/components/assets/ScenesPanel.tsx
  packages/editor/src/functions/sceneFunctions.tsx
  packages/server-core/src/assets/asset/asset.hooks.ts
  packages/server-core/src/assets/asset/asset.test.ts
Labels: verified-contributor

#10278 select dropdown arrow and tooltip text centering
  packages/ui/src/primitives/tailwind/Select/index.tsx
  packages/ui/src/primitives/tailwind/Tooltip/index.tsx
Labels: verified-contributor

#10279 Added new check-scope hook which will return true or false
  packages/server-core/src/hooks/check-scope.test.ts
  packages/server-core/src/hooks/check-scope.ts
Labels: verified-contributor

#10256 Update Scene Assets search
  packages/editor/src/components/assets/SceneAssetsPanel.tsx
  packages/engine/src/assets/classes/AssetLoader.ts
  packages/engine/src/assets/enum/AssetType.ts
Labels: verified-contributor

#10275 Updated prune_ecr_images to correctly handle private ECR repos.
  packages/server-core/src/projects/project/project-helper.ts
  scripts/build_and_publish_package.sh
  scripts/build_docker_builder.sh
  scripts/prune_ecr_images.ts
Labels: verified-contributor

#10289 IR-2372: Fix save scene
  packages/editor/src/functions/sceneFunctions.tsx
  packages/server-core/src/assets/asset/asset.hooks.ts
Labels: verified-contributor

#10260 Fixed bug in scope creation when scope exists
  packages/server-core/src/scope/scope/scope.hooks.ts
Labels: verified-contributor

#10290 fix entity node editor crashing
  packages/ui/src/components/editor/panels/Properties/container/index.tsx
Labels: verified-contributor

#10247 [IR-2055] Unit Test - Camera
  packages/ecs/src/SystemFunctions.ts
  packages/spatial/src/camera/systems/CameraSystem.test.tsx
  packages/spatial/src/camera/systems/SpectateSystem.test.tsx
Labels: verified-contributor

#10293 Various studio bug fixes
  packages/editor/src/components/properties/SceneSettingsEditor.tsx
  packages/editor/src/functions/uploadEnvMapBake.ts
  packages/engine/src/gltf/GLTFComponent.tsx
  packages/spatial/src/renderer/WebGLRendererSystem.tsx
  packages/ui/src/components/editor/input/String/index.tsx
  packages/ui/src/components/editor/properties/image/index.tsx
Labels: verified-contributor

#10214 IR-2153: replace scope checks with project permission checks
  packages/client-core/src/admin/common/Location/LocationDrawer.tsx
  packages/client-core/src/user/useUserProjectPermission.tsx
  packages/common/src/schemas/projects/project-permission.schema.ts
  packages/editor/src/components/toolbar/tools/PublishLocation.tsx
  packages/server-core/src/hooks/resolve-project-id.test.ts
  packages/server-core/src/hooks/resolve-project-id.ts
  packages/server-core/src/hooks/verify-project-permission.test.ts
  packages/server-core/src/hooks/verify-project-permission.ts
  packages/server-core/src/projects/project-permission/project-permission.hooks.ts
  packages/server-core/src/social/location/location.hooks.ts
Labels: verified-contributor

#10272 Add File Browser Search
  packages/server-core/src/media/file-browser/file-browser.class.ts
  packages/server-core/src/media/file-browser/file-browser.test.ts
Labels: verified-contributor

#10285 IR-1922 file processing bug on drag/drop
  packages/editor/src/components/inputs/FileBrowserInput.tsx
  packages/ui/src/components/editor/input/FileBrowser/index.tsx
Labels: verified-contributor

#10294 fix the white lines appearing between panels in studio
  packages/editor/src/components/Editor2Container.tsx
  packages/ui/src/components/editor/panels/Viewport/container/index.tsx
Labels: verified-contributor

#10297 IR-2109 Fix material renaming
  packages/ui/src/components/editor/panels/Properties/material/index.tsx
Labels: verified-contributor

#10287 IR-2365 Fix erroneous material updates and prototype switching errors
  packages/editor/src/components/assets/AssetPreviewPanels/MaterialPreviewPanel.tsx
  packages/spatial/src/renderer/materials/materialFunctions.ts
Labels: verified-contributor

#10234 Updated Cloudfront function to pass most things as routes
  packages/client/src/route/public.tsx
  packages/server-core/src/media/storageprovider/s3.storage.ts
Labels: verified-contributor

#10235 fix model transform in model component editor
  packages/editor/src/components/properties/ModelTransformProperties.tsx
  packages/engine/src/assets/compression/ModelTransformFunctions.ts
  packages/server-core/src/assets/model-transform/model-transform.class.ts
Labels: verified-contributor

#10284 Update email regex to more accurate one
  packages/common/src/config.ts
Labels: verified-contributor

#10271 GLTF LOD Compression
  packages/editor/src/components/assets/ImportSettingsPanel.tsx
Labels: verified-contributor

#10298 fix prototype changes losing material uuids
  packages/spatial/src/renderer/materials/materialFunctions.ts
Labels: verified-contributor

#10085 UVOL Refactor
  packages/editor/src/components/inputs/StringInput.tsx
  packages/editor/src/components/properties/NewVolumetricNodeEditor.tsx
  packages/editor/src/components/properties/PlaylistNodeEditor.tsx
  packages/editor/src/components/properties/PositionalAudioNodeEditor.tsx
  packages/editor/src/services/ComponentEditors.tsx
  packages/editor/src/services/ComponentShelfCategoriesState.ts
  packages/engine/src/scene/SceneModule.ts
  packages/engine/src/scene/components/NewVolumetricComponent.ts
  packages/engine/src/scene/components/PlaylistComponent.ts
  packages/engine/src/scene/constants/NewUVOLTypes.ts
  packages/engine/src/scene/util/BufferDataContainer.ts
  packages/engine/src/scene/util/VolumetricBufferingUtils.ts
  packages/engine/src/scene/util/VolumetricUtils.ts
Labels: verified-contributor

#10301 Ir 2392 MUI regression
  packages/client/src/main.tsx
  packages/client/src/pages/_app.tsx
  packages/editor/src/components/EditorContainer.tsx
Labels: verified-contributor

#10300 IR-1293 click to select mesh objects in scene edit mode
  packages/editor/src/systems/EditorControlSystem.tsx
  packages/spatial/src/input/systems/ClientInputSystem.tsx
  packages/ui/src/components/editor/properties/link/index.tsx
  packages/ui/src/components/editor/properties/mountPoint/index.tsx
Labels: verified-contributor
